### ISSUE TITLE
  markdown_to_html.r markdown built with different version : using local lib?

### ISSUE THREAD

**Issue by AlastairKerr** [nf-core/chipseq#100]
I have an error trying to run the chipseq pipeline via singularity. It complains that the markdown library has been built using a different version of R ( which happens to be same as what is in my local user library). It then tries to install it into my local library but (thankfully) make is not on the path.
 
'nfcore-chipseq-1.0.0.img'
 
```
ERROR ~ Error executing process > 'output_documentation'

Caused by:
  Process `output_documentation` terminated with an error exit status (1)

Command executed:

  markdown_to_html.r output.md results_description.html

Command exit status:
  1

Command output:
  (empty)

Command error:
  Loading required package: markdown
  Failed with error:  ‘package ‘markdown’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version’
  In addition: Warning message:
  package ‘markdown’ was built under R version 3.5.3
  Installing package into #<local path>#   R/x86_64-pc-linux-gnu-library/3.5’
  (as ‘lib’ is unspecified)
  trying URL 'http://cloud.r-project.org/src/contrib/markdown_1.0.tar.gz'
  Content type 'application/x-gzip' length 80843 bytes (78 KB)
  ==================================================
  downloaded 78 KB

  * installing *source* package ‘markdown’ ...
  ** package ‘markdown’ successfully unpacked and MD5 sums checked
  ** libs
  sh: 1: make: not found
  ERROR: compilation failed for package ‘markdown’
  * removing #<local path>#   R/x86_64-pc-linux-gnu-library/3.5/markdown’
  * restoring previous ‘#<local path>#   R/x86_64-pc-linux-gnu-library/3.5/markdown’

  The downloaded source packages are in
        ‘/tmp/311578/RtmptEzm3X/downloaded_packages’
  Error: package ‘markdown’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
  In addition: Warning messages:
  1: In install.packages("markdown", dependencies = TRUE, repos = "http://cloud.r-project.org/") :
    installation of package ‘markdown’ had non-zero exit status
  2: package ‘markdown’ was built under R version 3.5.3
  Execution halted

```

**Comment by drpatelh** [comment]
Hi @AlastairKerr ! Thanks for running the pipeline. The process shouldnt need to try and install `markdown` because it will already be in the `singularity` image.

Can you send me the command you are using please? Im assuming you have `singularity` installed?

**Comment by drpatelh** [comment]
Its always worth trying to get the `test` profile running if this is the first time you are using an `nf-core` pipeline.

So assuming you have `Nextflow` and `Singularity` on your path you could try and run:
`nextflow run nf-core/chipseq -profile test,singularity`

**Comment by AlastairKerr** [comment]
command I used : 
nohup nextflow run nf-core/chipseq --design design.tsv --genome R64-1-1 -profile singularity  &

nf-core was working and the image downloaded to my cache with no issues.

I've used the rnaseq pipeline in nf-core before with no errors. 

Output using 
nohup nextflow run nf-core/chipseq -profile test,singularity -with-singularity /<localpath>/nfcore-chipseq-1.0.0.img --design design.tsv --genome R64-1-1 &

I get the same error 
* markdown built with a different version, 
* attempting to download  
* make error (not found in path)

**Comment by drpatelh** [comment]
Hmmm...`markdown` is definitely in the container. I can load it in `R` once in the image:
`singularity shell nfcore-chipseq-1.0.0.img` 

I wonder if its got something to do with an `R` environment variable lying around thats over-riding the version in the image.

**Comment by drpatelh** [comment]
Do any of these commands give you the same path as `#<local path>#` in the above error trace? If so, it probably means that it needs to be unset.

`R RHOME`
`echo $R_HOME`
`echo $PATH`

**Comment by AlastairKerr** [comment]
Thanks, this has helped me track down the error. 
.libPaths() was being set in my .Rprofile and being imported into the container.  The libs in the container had less priority than the environment. 

I'm not sure what would be the easiest solution.  Maybe remove this file and try and set an environmental variable instead that I can unset in my nextflow.config.

**Comment by ewels** [comment]
I've had similar issues in the past with conda inheriting environment variables from outside the container. It's not great! It would be ideal if there was a way to totally isolate the running environment from the host env vars... 🤔
