### ISSUE TITLE
Chromosome 10 error in fasta files

### ISSUE THREAD

**Issue by jkobject** [nf-core/chipseq#101]
Hello, 

running the command `nextflow run nf-core/chipseq --singleEnd --outdir data/results --seq_center 'DFCI' --email '[].com' --skipDiffAnalysis --narrowPeak --design singleend.csv --max_cpus 8 --max_memory "12.GB" --genome GRCh37 -profile docker`

on a list of single_end fastq files and always get this cryptic error.

`Chromosome "10" undefined in genome.fa.sizes nf-core`

Using GRCh38. I get the same one but with "chr10". I don't get where the problem comes from.

Thanks! 

And thanks for the amazing pipelines

**Comment by jkobject** [comment]
genomes.fa.sizes only contains:
```
1       249250621
2       243199373
3       198022430
4       187821810
```

**Comment by drpatelh** [comment]
Hi @jkobject ! This is really odd. It appears like you are downloading the genome from AWS iGenomes at run time so could it be a download issue? This obviously doesnt explain why you are seeing the same error from another reference assembly though 🤔 

Can you maybe try to download the reference assembly directly using the link below:
https://ewels.github.io/AWS-iGenomes/

and then provide an additional parameter `--fasta <PATH_TO_FASTA_FILE>`

**Comment by drpatelh** [comment]
Can you search for `genome.fa.sizes` in the work directory and send me the other files in that directory too i.e. `genome.fa.fai`, and `genome.fa.include_regions.bed`
`find ./work/ -type f -name genome.fa.sizes`

**Comment by drpatelh** [comment]
Hi @jkobject . Have you managed to figure out what was happening? Still puzzled TBH!

**Comment by drpatelh** [comment]
There seem to be issues here on multiple-levels! Have you tried just running the `test` profile for the pipeline? i.e.
`nextflow run nf-core/chipseq -profile test,docker`

I think its a good idea to get this working first before you use it on your test-dataset.

Also, are you able to run the pipeline using `singularity` as opposed to `docker`?

**Comment by drpatelh** [comment]
Ahhh, you are running on `Google Cloud Platform`?

**Comment by drpatelh** [comment]
These sorts of bucket-related file issues do tend to prop up quite often with Cloud deployment. Unfortunately, Im not very familiar with GCP but it may be worth asking on the Nextflow Gitter channel or creating an issue there? Sorry!

**Comment by jkobject** [comment]
Hello I now get a new error, continuing on the pipeline. it seems to be at the preseq task which worked for 31 sequences but seemed to have failed on the 32 one.
the error: 
```shell
(base) jeremie@broadprojects:~/AMLproject/work/90/0cfb0983cfb3c2603cf63b4fdf95d0$ bash .command.run
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
BAM_INPUT
TOTAL READS     = 68805232
DISTINCT READS  = 2.68731e+07
DISTINCT COUNTS = 582
MAX COUNT       = 2165
COUNTS OF 1     = 6.09103e+06
MAX TERMS       = 100
OBSERVED COUNTS (2166)
1	6091033
2	12935345
3	1661364
4	3861018
5	618583
6	1044581
7	195403
8	256123
9	57109
10	61142
.......
788	1
797	2
802	1
846	2
849	1
851	1
852	1
853	1
860	1
872	1
886	2
894	1
902	1
929	1
936	1
937	1
943	1
948	1
949	1
952	1
975	1
993	1
997	1
1004	1
1021	1
1031	1
1091	1
1141	1
1195	1
1235	1
1271	1
1278	1
1300	1
1345	1
1391	1
1490	1
1542	1
1642	1
2165	1

ERROR:	Library expected to saturate in doubling of size, unable to extrapolate
```
I don't understand it. And I don't get much more than that. Thanks!

**Comment by drpatelh** [comment]
There is some explanation for this in the manual if you search for the error:
http://smithlabresearch.org/wp-content/uploads/manual.pdf

Im not entirely sure what this means either and Ive never seen that error before :sweat_smile: but other than contacting the authors of the software the easiest way around this would be to specify the `--skipPreseq` parameter when using `-resume`. This should bypass this step.

**Comment by jkobject** [comment]
Yes I have seen this explanation but it is not very substantial. So if I run the same command than before with -resume it should start back from where it was? (thanks to docker and you, dr. Pathel)

**Comment by drpatelh** [comment]
Yep just add `-resume --skipPreseq` and the pipeline should start from where it left off and skip the `preseq` step :+1:

**Comment by jkobject** [comment]
Hello, 

One last problem before I close this issue. I have to process also paired end data. however my input is single end. Is there anything I can do?

**Comment by drpatelh** [comment]
Ah, you have a mix of single-end and paired-end data? The pipeline will only handle one or the other and not both. Its a bit tricky to wire this sort of functionality into the pipeline because different tools have different parameters for single-end and paired-end data, and the filtering is also very different because you have to factor in both reads of the pair.

Its fine to just use read 1 from the paired-end data and treat everything as single-end. The peaks and downstream results should be quite similar overall especially with the read lengths we tend to get nowadays. If you want, you can test the pipeline in both paired-end and single-end mode to see if there are any differences.

**Comment by jkobject** [comment]
I understand. thank for this experienced feedback. I will run it on single_end pipeline then!
Best,
