### ISSUE TITLE
makeGenomeFilter error 

### ISSUE THREAD

**Issue by jidiazhernandez** [nf-core/chipseq#103]
Hi to all, 
after upgrading nexflow from version 18 to version 19 I started to get an error when I ran the pipeline:

```bash
nextflow run nf-core/chipseq --design design_file.csv --genome hg19 -profile docker --singleEnd --narrowPeak --saveMACSPileup
```

in the MakeGenomeFilter process, obtaining the following error:

```
Error executing process > 'makeGenomeFilter (genome.fa)'

Caused by:
  Process `makeGenomeFilter (genome.fa)` terminated with an error exit status (1)

Command executed:

  samtools faidx genome.fa
  cut -f 1,2 genome.fa.fai > genome.fa.sizes
  sortBed -i /home/jidiaz/.nextflow/assets/nf-core/chipseq/assets/blacklists/hg19-blacklist.bed -g genome.fa.sizes | complementBed -i stdin -g genome.fa.sizes > genome.fa.include_regions.bed

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error: The requested file (/home/jidiaz/.nextflow/assets/nf-core/chipseq/assets/blacklists/hg19-blacklist.bed) could not be opened. Error message: (No such file or directory). Exiting!
```

I check the file exists and have reading permissions, as well as copy it to other location and get the very same error.

I check that is a repeated issue, but the permissions issue suggested don't work in my case
Thank you very much

**Comment by drpatelh** [comment]
Hi @jidiazhernandez ! This is actually a bug in the pipeline because the blacklist file isnt staged properly for that process. It seems to work for some and not others...

I am in the process of making some changes to the pipeline that will fix this in the `dev` version. For now, can you try and copy the file into the directory where you are running the pipeline and add `--blacklist hg19-blacklist.bed` as a parameter and let me know if that works.

**Comment by jidiazhernandez** [comment]
Hi @drpatelh,
I try your suggestion and it doesn't work.
Is there any method to copy the makeGenomeFilter files generated in previous successful pipelines and skip this step? I run the pipeline previously without any issue and the genome.fa.include_region.bed is in the results folder of these experiments.
Thank you for your time and patience.

**Comment by drpatelh** [comment]
Hi @jidiazhernandez. Ok. I'll try and push the fix to the `dev` branch of the pipeline today. I have changed some other bits in the pipeline too so if you are comparing results with previous runs of the pipeline then you should still use the current version (v1.0.0), in which case it would be easier to downgrade the version of Nextflow because that was working for you. 

However, it would be good if you can test the `dev` version of the pipeline when I have pushed the changes just to make sure it's fixed - you will be able to do this by adding the `-r dev` parameter. I'll let you know when I've pushed the changes.

**Comment by drpatelh** [comment]
Unfortunately, you can't provide `genome.fa.include_region.bed` as a parameter because it has to be generated from the blacklist file. This step can be quite problematic which is why I have implemented it this way.

**Comment by drpatelh** [comment]
Hi @jidiazhernandez I have merged the fix into `dev` now. If you want to try it out you can delete your local copy of the pipeline:
`rm -rf ~/.nextflow/assets/nf-core/chipseq/`

and just add the `-r dev` parameter when you are running the pipeline. Be good if it works now :sweat_smile:

**Comment by jidiazhernandez** [comment]
Dear @drpatelh , 
I've tried the dev version, but without success, indeed, this time crashes in an early step. I paste the output and the .nextflow.log for our information 

(base) jidiaz:nc_core_analysis/ $ nextflow run nf-core/chipseq --design design_file.csv --genome hg19 -profile docker --singleEnd  --narrowPeak --saveMACSPileup -r dev
N E X T F L O W  ~  version 19.07.0
Launching `nf-core/chipseq` [nasty_tuckerman] - revision: 6308c1b4b6 [dev]
WARN: Access to undefined parameter `gene` -- Initialise it to a default value eg. `params.gene = some_value`
Cannot get property 'bed' on null object

 -- Check script '/home/jidiaz/.nextflow/assets/nf-core/chipseq/main.nf' at line: 160 or see '.nextflow.log' file for more details
(base) jidiaz:nc_core_analysis/ $ more .nextflow.log                                                                                                                               [9:52:01]
Oct-07 09:51:47.109 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/chipseq --design design_file.csv --genome hg19 -profile docker --singleEnd --narrowPeak --saveMACSPileup -r dev
Oct-07 09:51:47.281 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.07.0
Oct-07 09:51:48.025 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/jidiaz/.nextflow/assets/nf-core/chipseq/.git/config; branch: master; remote: origin; url: https://github.com/n
f-core/chipseq.git
Oct-07 09:51:48.034 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/jidiaz/.nextflow/assets/nf-core/chipseq/.git/config; branch: master; remote: origin; url: https://github.com/n
f-core/chipseq.git
Oct-07 09:51:48.310 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/jidiaz/.nextflow/assets/nf-core/chipseq/.git/config; branch: master; remote: origin; url: https://github.com/n
f-core/chipseq.git
Oct-07 09:51:48.310 [main] INFO  nextflow.cli.CmdRun - Launching `nf-core/chipseq` [nasty_tuckerman] - revision: 6308c1b4b6 [dev]
Oct-07 09:51:54.032 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/jidiaz/.nextflow/assets/nf-core/chipseq/nextflow.config
Oct-07 09:51:54.033 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/jidiaz/.nextflow/assets/nf-core/chipseq/nextflow.config
Oct-07 09:51:54.042 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `docker`
Oct-07 09:51:59.734 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [uppmax_devel, bigpurple, uppmax, docker, gis, ccga, conda, singularity, munin, prince, czbiohub_
aws, hebbe, cfc, uzh, debug, test, cbe, ccga_dx, crick, czbiohub_aws_highpriority, kraken, phoenix, shh, mendel, pasteur, uct_hex, awsbatch, binac]
Oct-07 09:51:59.886 [main] DEBUG nextflow.Session - Session uuid: b4d38f84-8e21-4b36-b32f-1e43721df428
Oct-07 09:51:59.886 [main] DEBUG nextflow.Session - Run name: nasty_tuckerman
Oct-07 09:51:59.887 [main] DEBUG nextflow.Session - Executor pool size: 36
Oct-07 09:51:59.900 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 19.07.0 build 5106
  Created: 27-07-2019 13:22 UTC (15:22 CEST)
  System: Linux 5.0.0-31-generic
  Runtime: Groovy 2.5.6 on OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
  Encoding: UTF-8 (UTF-8)
  Process: 4506@WKS-HPL-724 [127.0.1.1]
  CPUs: 36 - Mem: 251.8 GB (246.3 GB) - Swap: 0 (0)
Oct-07 09:51:59.925 [main] DEBUG nextflow.Session - Work-dir: /media/jidiaz/Data/Projects/PM01183/SCLC/20191001_chipseq_DMS53_2/nc_core_analysis/work [ext2/ext3]
Oct-07 09:52:00.862 [main] DEBUG nextflow.Session - Session start invoked
Oct-07 09:52:00.865 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /media/jidiaz/Data/Projects/PM01183/SCLC/20191001_chipseq_DMS53_2/nc_core_analysis/results/p
ipeline_info/execution_trace.txt
Oct-07 09:52:01.568 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Oct-07 09:52:01.606 [main] WARN  nextflow.script.ScriptBinding - Access to undefined parameter `gene` -- Initialise it to a default value eg. `params.gene = some_value`
Oct-07 09:52:01.607 [main] DEBUG nextflow.Session - Session aborted -- Cause: Cannot get property 'bed' on null object
Oct-07 09:52:01.616 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.NullPointerException: Cannot get property 'bed' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at Script_19edc4fc.runScript(Script_19edc4fc:160)
	at nextflow.script.BaseScript.run(BaseScript.groovy:151)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:189)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:287)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:132)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:246)
	at nextflow.cli.Launcher.run(Launcher.groovy:451)
	at nextflow.cli.Launcher.main(Launcher.groovy:633)
I hope you find useful

**Comment by drpatelh** [comment]
Hi @jidiazhernandez ! Thanks for giving this a go. You are indeed right. There was a bug in the `gene_bed` parameter name. I have fixed this and created a PR https://github.com/nf-core/chipseq/pull/107. When the tests pass Ill merge this and you can follow the same process to run the `dev` version. 

This kind of thing only becomes apparent with a proper dataset and not the test dataset we use for continuous integration. Thank you!

**Comment by drpatelh** [comment]
Merged now @jidiazhernandez 👍

**Comment by jidiazhernandez** [comment]
Hi @drpatelh, 
the new version dev version has two other issues,
the first one, now i need a bed reference files instead the gtf, but this was quickly fixed, only for your information.
and the second one appear to be more problematic, I attach the nextflow.log for your reference
nextflow run nf-core/chipseq --design design_file.csv --genome hg19 -profile docker --singleEnd --igenomes_base /media/jidiaz/Data/Genomic_index/references --narrowPeak --saveMACSPileup -r dev
N E X T F L O W  ~  version 19.07.0
Launching `nf-core/chipseq` [boring_noyce] - revision: 0dda84544c [dev]
[2m----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/chipseq v1.0.1dev
----------------------------------------------------
Run Name            : boring_noyce
Data Type           : Single-End
Design File         : design_file.csv
Genome              : hg19
Fasta File          : /media/jidiaz/Data/Genomic_index/references/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa
GTF File            : /media/jidiaz/Data/Genomic_index/references/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf
Gene BED File       : /media/jidiaz/Data/Genomic_index/references/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.bed
BWA Index           : /media/jidiaz/Data/Genomic_index/references/Homo_sapiens/UCSC/hg19/Sequence/BWAIndex/genome.fa
Blacklist BED       : /home/jidiaz/.nextflow/assets/nf-core/chipseq/assets/blacklists/hg19-blacklist.bed
MACS2 Genome Size   : 2.7e9
Min Consensus Reps  : 1
MACS2 Narrow Peaks  : Yes
Trim R1             : 0 bp
Trim R2             : 0 bp
Trim 3' R1          : 0 bp
Trim 3' R2          : 0 bp
Fragment Size       : 200 bp
Fingerprint Bins    : 500000
Save Genome Index   : No
Save MACS2 Pileup   : Yes
Max Resources       : 128 GB memory, 16 cpus, 10d time per job
Container           : docker - nfcore/chipseq:dev
Output Dir          : ./results
Launch Dir          : /media/jidiaz/Data/Projects/PM01183/SCLC/20191001_chipseq_DMS53_2/nc_core_analysis
Working Dir         : /media/jidiaz/Data/Projects/PM01183/SCLC/20191001_chipseq_DMS53_2/nc_core_analysis/work
Script Dir          : /home/jidiaz/.nextflow/assets/nf-core/chipseq
User                : jidiaz
Config Profile      : docker
[2m----------------------------------------------------
[-        ] process > CheckDesign -
[-        ] process > MakeTSSBED  -
Unknown method `ifEmpty` on UnixPath type

 -- Check script '/home/jidiaz/.nextflow/assets/nf-core/chipseq/main.nf' at line: 416 or see '.nextflow.log' file for more details

(base) jidiaz:nc_core_analysis/ $ more .nextflow.log                                                                                                                              [14:53:02]
Oct-07 14:52:49.016 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/chipseq --design design_file.csv --genome hg19 -profile docker --singleEnd --igenomes_base /media/jidiaz/Dat
a/Genomic_index/references --narrowPeak --saveMACSPileup -r dev
Oct-07 14:52:49.126 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.07.0
Oct-07 14:52:49.848 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/jidiaz/.nextflow/assets/nf-core/chipseq/.git/config; branch: master; remote: origin; url: https://github.com/n
f-core/chipseq.git
Oct-07 14:52:49.856 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/jidiaz/.nextflow/assets/nf-core/chipseq/.git/config; branch: master; remote: origin; url: https://github.com/n
f-core/chipseq.git
Oct-07 14:52:50.155 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/jidiaz/.nextflow/assets/nf-core/chipseq/.git/config; branch: master; remote: origin; url: https://github.com/n
f-core/chipseq.git
Oct-07 14:52:50.155 [main] INFO  nextflow.cli.CmdRun - Launching `nf-core/chipseq` [boring_noyce] - revision: 0dda84544c [dev]
Oct-07 14:52:55.804 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/jidiaz/.nextflow/assets/nf-core/chipseq/nextflow.config
Oct-07 14:52:55.805 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/jidiaz/.nextflow/assets/nf-core/chipseq/nextflow.config
Oct-07 14:52:55.814 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `docker`
Oct-07 14:53:01.503 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [uppmax_devel, bigpurple, uppmax, docker, gis, ccga, conda, singularity, munin, prince, czbiohub_
aws, hebbe, cfc, uzh, debug, test, cbe, ccga_dx, crick, czbiohub_aws_highpriority, kraken, phoenix, shh, mendel, pasteur, uct_hex, awsbatch, binac]
Oct-07 14:53:01.540 [main] DEBUG nextflow.Session - Session uuid: 51f4eb41-606a-45ba-89ad-6c3dcc25c046
Oct-07 14:53:01.541 [main] DEBUG nextflow.Session - Run name: boring_noyce
Oct-07 14:53:01.541 [main] DEBUG nextflow.Session - Executor pool size: 36
Oct-07 14:53:01.550 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 19.07.0 build 5106
  Created: 27-07-2019 13:22 UTC (15:22 CEST)
  System: Linux 5.0.0-31-generic
  Runtime: Groovy 2.5.6 on OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
  Encoding: UTF-8 (UTF-8)
  Process: 20928@WKS-HPL-724 [127.0.1.1]
  CPUs: 36 - Mem: 251.8 GB (173.1 GB) - Swap: 0 (0)
Oct-07 14:53:01.564 [main] DEBUG nextflow.Session - Work-dir: /media/jidiaz/Data/Projects/PM01183/SCLC/20191001_chipseq_DMS53_2/nc_core_analysis/work [ext2/ext3]
Oct-07 14:53:01.712 [main] DEBUG nextflow.Session - Session start invoked
Oct-07 14:53:01.716 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /media/jidiaz/Data/Projects/PM01183/SCLC/20191001_chipseq_DMS53_2/nc_core_analysis/results/p
ipeline_info/execution_trace.txt
Oct-07 14:53:02.435 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Oct-07 14:53:02.560 [main] INFO  nextflow.Nextflow - ----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/chipseq v1.0.1dev
----------------------------------------------------

Oct-07 14:53:02.565 [main] INFO  nextflow.Nextflow - Run Name            : boring_noyce
Data Type           : Single-End
Design File         : design_file.csv
Genome              : hg19
Fasta File          : /media/jidiaz/Data/Genomic_index/references/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa
GTF File            : /media/jidiaz/Data/Genomic_index/references/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf
Gene BED File       : /media/jidiaz/Data/Genomic_index/references/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.bed
BWA Index           : /media/jidiaz/Data/Genomic_index/references/Homo_sapiens/UCSC/hg19/Sequence/BWAIndex/genome.fa
Blacklist BED       : /home/jidiaz/.nextflow/assets/nf-core/chipseq/assets/blacklists/hg19-blacklist.bed
MACS2 Genome Size   : 2.7e9
Min Consensus Reps  : 1
MACS2 Narrow Peaks  : Yes
Trim R1             : 0 bp
Trim R2             : 0 bp
Trim 3' R1          : 0 bp
Trim 3' R2          : 0 bp
Fragment Size       : 200 bp
Fingerprint Bins    : 500000
Save Genome Index   : No
Save MACS2 Pileup   : Yes
Max Resources       : 128 GB memory, 16 cpus, 10d time per job
Container           : docker - nfcore/chipseq:dev
Output Dir          : ./results
Launch Dir          : /media/jidiaz/Data/Projects/PM01183/SCLC/20191001_chipseq_DMS53_2/nc_core_analysis
Working Dir         : /media/jidiaz/Data/Projects/PM01183/SCLC/20191001_chipseq_DMS53_2/nc_core_analysis/work
Script Dir          : /home/jidiaz/.nextflow/assets/nf-core/chipseq
User                : jidiaz
Config Profile      : docker
Oct-07 14:53:02.565 [main] INFO  nextflow.Nextflow - ----------------------------------------------------
Oct-07 14:53:02.617 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Oct-07 14:53:02.618 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Oct-07 14:53:02.622 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Oct-07 14:53:02.624 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=36; memory=251.8 GB; capacity=36; pollInterval=100ms; dumpInterval
=5m
Oct-07 14:53:02.660 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > CheckDesign -- maxForks: 36
Oct-07 14:53:02.728 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Oct-07 14:53:02.728 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Oct-07 14:53:02.730 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > MakeTSSBED -- maxForks: 36
Oct-07 14:53:02.765 [main] DEBUG nextflow.Session - Session aborted -- Cause: No signature of method: sun.nio.fs.UnixPath.ifEmpty() is applicable for argument types: (ArrayList) values: [[]
]
Possible solutions: isEmpty(), empty(), first()
Oct-07 14:53:02.793 [main] DEBUG nextflow.Session - The following nodes are still active:
[process] CheckDesign
  status=ACTIVE
  port 0: (value) bound ; channel: design
  port 1: (cntrl) -     ; channel: $

[process] MakeTSSBED
  status=ACTIVE
  port 0: (value) bound ; channel: bed
  port 1: (cntrl) -     ; channel: $

Oct-07 14:53:02.838 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingMethodException: No signature of method: sun.nio.fs.UnixPath.ifEmpty() is applicable for argument types: (ArrayList) values: [[]]
Possible solutions: isEmpty(), empty(), first()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at Script_203aadf9$_runScript_closure15.doCall(Script_203aadf9:416)
	at Script_203aadf9$_runScript_closure15.doCall(Script_203aadf9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at nextflow.script.ProcessFactory.createProcessor(ProcessFactory.groovy:109)
	at nextflow.script.ProcessFactory.createProcessor(ProcessFactory.groovy)
	at nextflow.script.ProcessFactory$createProcessor.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at nextflow.script.ProcessFactory$createProcessor.call(Unknown Source)
	at nextflow.script.BaseScript.process(BaseScript.groovy:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at Script_203aadf9.runScript(Script_203aadf9:410)
	at nextflow.script.BaseScript.run(BaseScript.groovy:151)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:189)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:287)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:132)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:246)
	at nextflow.cli.Launcher.run(Launcher.groovy:451)
	at nextflow.cli.Launcher.main(Launcher.groovy:633)

But there is also good news, I also have created a link (soft link) for the blacklist file in the igenomes reference folder instead of copying it and seems to work in the master branch with nextflow v18.10.1. I will try with the last version of nextflow and I will keep you informed of the progression.
Thank you very much for your patience and time.

**Comment by ewels** [comment]
_[Editor's note]: Using [triple backticks](https://guides.github.com/features/mastering-markdown/) makes pasted code in markdown much easier to read 😉_

**Comment by jidiazhernandez** [comment]
dear @drpatelh 
I have been able to run the pipeline withoun any issue either in nextoflow 18 and nextflow 19 creating a soft link of the blacklist in the reference folder I use. It does not work copying the file, only with the link, I do not understand why, but it works.
Thank you for your patience, time and kindness

**Comment by jidiazhernandez** [comment]
> _[Editor's note]: Using [triple backticks](https://guides.github.com/features/mastering-markdown/) makes pasted code in markdown much easier to read wink_

I change it, than you for the markdown suggestions

**Comment by drpatelh** [comment]
Hi @jidiazhernandez . Thanks for the response and sorting out the code blocks :wink:

Ok. So the bed file issue you were having was because you were using a local `iGenomes` area where the bed file wasnt present i.e. you didnt download it from [AWS iGenomes](https://github.com/ewels/AWS-iGenomes)? If so, then yes just adding it there should solve that issue.

The pipeline should work without you having to soft-link the blacklist file. We need to figure out why its failing. I have an idea.... Its basically this line:
https://github.com/nf-core/chipseq/blob/0dda84544c13474db67bc98b3e84ebe8f3bbcbe7/main.nf#L416

Since the blacklist parameter isnt mandatory I have to find a way to pass the blacklist file to the `MakeGenomeFilter` process even when it isnt supplied. However, when it is supplied then its a NF file object which doesnt inherit the `.ifEmpty([])` functionality :confused: 

Ill keep this issue open until I have run some more extensive tests and let you know. It would be great if you could test again at that point. Thanks!

**Comment by jidiazhernandez** [comment]
Hi @drpatelh , 
I download iGenomes from AWS iGenomes, and I find the link there and direct by adding the -blacklist parameter, and then it works. If I copy the blacklist bed file from nf-core/chip-seq folder to the design.csv folder and pointed with de - blacklist parameter it didn't work. I'm not sure if this information is useful in any way.
Of course I can test it again
Thank you

**Comment by drpatelh** [comment]
Hi @jidiazhernandez You shouldnt need to use the `--blacklist` parameter now because I the bug should be fixed now. I have merged the changes into `dev` for you to test. Im hoping it works now 😅
