### ISSUE TITLE
Running the pipeline on different filesystem

### ISSUE THREAD

**Issue by nandobonf** [nf-core/chipseq#104]
Dear authors,
I can successfully run the test pipeline in my HPC home directory with the command:
`nextflow run nf-core/chipseq -with-singularity /raid/playground/nextflow.test/nfcore.chipseq.simg -profile test,singularity --max_cpus 16`
but when I run the same command on an attached raid or a scratch system I get the error message pasted below.
I also tested different commands, ie, without downloading the singularity image, but I get the same error message. Is there any specific parameter to set to make it work when running it on raid/scratch file sys?
Thanks for the precious help.

```
#nextflow run nf-core/chipseq -with-singularity /raid/playground/nextflow.test/nfcore.chipseq.simg -profile test,singularity --max_cpus 16

Error executing process > 'checkDesign (design.csv)'

Caused by:
  Process `checkDesign (design.csv)` terminated with an error exit status (127)

Command executed:

  check_design.py design.csv design_reads.csv design_controls.csv

Command exit status:
  127

Command output:
  (empty)

Command error:
  /bin/bash: line 0: cd: /raid/playground/nextflow.test/work/29/f881a37a9b57e1707c25ad38763283: No such file or directory
  /bin/bash: .command.run: No such file or directory

```

**Comment by drpatelh** [comment]
Hi @nandobonf . It appears that the `work` directories arent being mounted in the Singularity image when Nextflow is running.

Can you create a file called `custom.config` with the following lines:

```
singularity {
  enabled = true
  autoMounts = true
}
```

and then run the pipeline with an additional parameter `-c custom.config`.

**Comment by nandobonf** [comment]
Hi @drpatelh, thanks for the swift reply. With the custom config it works pretty well. Thanks!

**Comment by drpatelh** [comment]
Cool. Thanks for letting me know @nandobonf 👍
