### ISSUE TITLE
Error in bigWig generation step

### ISSUE THREAD

**Issue by ilakya-selvarajan** [nf-core/chipseq#110]
Hi!

I'm running nf-core/ChipSeq for few paired-end samples. The run is successful for few steps (image: 
![image](https://user-images.githubusercontent.com/8700495/67265086-83436200-f4b5-11e9-879b-4a8e8020a60b.png), but fails at creating bigWig files.

The error is attached : 
![image](https://user-images.githubusercontent.com/8700495/67265135-a8d06b80-f4b5-11e9-9618-70d257a67487.png)

Any suggestion? Please let me know. Thanks!

**Comment by drpatelh** [comment]
Hi @ilakya-selvarajan ! From the error it seems like you dont have a `tmp` directory environment variable set on your system which is required by the `sort` command. 

Does `cd /tmp/` exist on your system?

If so, can you add the line below before you execute the command for the pipeline:
`export $TMPDIR=/tmp/`

and then resume the pipeline by adding `-resume` to the command.

Let me know if that works :+1:

**Comment by ilakya-selvarajan** [comment]
Awesome! Thank you :) I'll close this issue.
