### ISSUE TITLE
nf-core on gcp

### ISSUE THREAD

**Issue by jkobject** [nf-core/chipseq#117]
Hello, 

It is not really an issue but more a call for help. (I wanted to ask on slack but got a 404 for this page https://nf-co.re/join/slack/).

I have not been able to understand how to configure nfcore for computing on gcp. I have seen how to parametrize nextflow to do it but I don't know how it will get the file, how to choose the right docker container etc..

I am guessing it needs to be a good config of both nf-core/configs and netflows.config.
I just don't know how to do it. 
Best,

**Comment by drpatelh** [comment]
Hi @jkobject . You should be able to see an option to join the Slack workspace using this link:
https://nf-co.re/join

I don't have any experience with GCP but hopefully someone should be able to help if you post a message on the `help` channel. Maybe we need to create a separate channel dedicated to GCP too.

Where did you see that broken link?

**Comment by jkobject** [comment]
Hello, 

Here is where the link is 'Slack' in https://nf-co.re/chipseq/docs/usage#custom-resource-requests. I will try to make a new config file for GCP and make a pull request if that works out.

Best,

**Comment by jkobject** [comment]
I have made a PR. This should be run like that: (Here I give an example)

`nextflow cloud create JKcluster -c 40`

```nextflow nf-core/chipseq --singleEnd --seq_center 'DFCI' --email 'jkobject@gmail.com' -bucket-dir 'gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/' -keyfile '~/jkobject-b6f1adaffcb8.json' -projectname 'jkobject' -zone 'us-east1-b' --skipDiffAnalysis --narrowPeak --design chip_analysis.csv --genome 'GRCh38' -profile gcp -resume --skipPreseq --max_cpus 8```

`nextflow cloud shutdown JKcluster`

**Comment by drpatelh** [comment]
Hi @jkobject . So based on that command I have restructured things slightly. 

For example, if you have a file called `custom.config` with the following contents:
```
cloud {
    driver = 'google'
    imageId = 'debian-9-stretch-v20191014'
    instanceType = 'n1-highcpu-8'
    userName = 'jkobject'
    keyfile= '~/jkobject-b6f1adaffcb8.json'
}

google {
    project = 'jkobject'
    zone = 'us-east1-b'
}
```

An updated command would like like this:
```
nextflow cloud create JKcluster -c 40

nextflow nf-core/chipseq \
    --input chip_analysis.csv \
    --genome 'GRCh38' \
    --single_end \
    --seq_center 'DFCI' \    
    --narrow_peak \
    --skip_diff_analysis \
    --skip_preseq \
    --max_cpus 8 \
    --email 'jkobject@gmail.com' \
    -r 1.1.0 \
    -c custom.config \
    -bucket-dir 'gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/' \
    -profile docker
    -resume

nextflow cloud shutdown JKcluster
```

Obviously, I dont have the ability to test this but something like that should work? You would need a container to run the pipeline which is why I have set `-profile docker` because that will automatically download the correct container for you. I have asked on the `#help` channel on the nf-core Slack workspace to see if anyone else has used GCP. Have you joined yet?

**Comment by drpatelh** [comment]
PS: That broken link should be working now. Thanks.

**Comment by jkobject** [comment]
Hello,

You are right. sorry about that. I learnt about the working of things as I made the PR and I figured that out later yesterday after making the PR. I am testing it now and had tons of difficulties for nextflow to find my imageId... I will write out a small "how to" to run on gcp. once I am done.

Best,

**Comment by drpatelh** [comment]
Hi @jkobject . How did you get on with getting the pipeline working on GCP?

**Comment by jkobject** [comment]
Hey,

I am waiting for some more INPUT data to launch the full processing but I
should get back to you about it next week.

Best,

Jérémie KALFON
Associate Computational Biologist @BroadInsitute of MIT and Harvard
M.eng. Biomedical Engineering / M.sc. Computational Intelligence
ECE Paris / University of Kent
CEO & Co-Founder @PiPle
jkobject@gmail.com <:jkobject@gmail.com>
jkobject.com
<https://gnldr.online/tracker/click?redirect=http%3A%2F%2Fjkobject.com%2F&dID=1574432499514&linkName=jkobject.com
>


Le ven. 22 nov. 2019 à 05:07, Harshil Patel <notifications@github.com> a
écrit :

**Comment by jkobject** [comment]
Hello,

I fall into an issue where I provide my config file 
```
cloud {
    driver = 'google'
    imageId = 'jkobject/global/images/dockerjava'
    instanceType = 'n1-highcpu-8'
    userName = 'jkobject'
    keyfile= '/home/jeremie/.ssh/id_rsa.pub'

}
google {
    project = 'jkobject'
    zone = 'us-east1-b'
}
```
and run `nextflow run nf-core/chipseq -c "nextflow/nextflow.config" --singleEnd --seq_center 'DFCI' --email 'jkobject@gmail.com' --bucket-dir 'gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/' --keyfile '~/jkobject-b6f1adaffcb8.json' --projectname 'jkobject' --zone 'us-east1-b' --skipDiffAnalysis --narrowPeak --design "nextflow/design.csv" --genome "GRCh38" --profile 'gcp' --resume --skipPreseq --max_cpus 8`

however it still displays a local working dir and then crashes. I think I might need to have a more complex config file

**Comment by jkobject** [comment]
I went into chipseq folder in `.nextflow/assest/nfcore` and modified the files there.
I added the content of my config file into the chipseq config file and created a dummy gcp profile with 
`  gcp { includeConfig 'conf/gcp.config' }` and gcp.config being:
```
params {
  config_profile_name = 'gcp'
  config_profile_description = 'gcp Cloud Profile'
  config_profile_contact = 'Alexander Peltzer (@apeltzer)'
  config_profile_url = 'https://cloud.google.com/'
}

process.executor = 'gcp'
process.queue = params.awsqueue
params.tracedir = './'
```

But it still gives a local working dir and crashes with a 
```
Command error:
    File "/home/jeremie/.nextflow/assets/nf-core/chipseq/bin/check_design.py", line 46
      print "{} header: {} != {}".format(ERROR_STR,','.join(header),','.join(HEADER))
                                                ^
  SyntaxError: invalid syntax
```

**Comment by drpatelh** [comment]
Hi @jkobject The parameters you are using to run the pipeline (as sent in this message https://github.com/nf-core/chipseq/issues/117#issuecomment-557683930) dont appear to be correct. You have to use single-dash for Nextflow parameters and double-dash for the pipeline parameters. Also, the pipeline parameter names have now been changed to follow `snake_case` for the latest version of the pipeline (`v1.1.1`). I would definitely recommend running the latest. Just delete your local version first using:
`rm -r ~/.nextflow/assets/nf-core/chipseq/`

I have also re-formatted and corrected the parameters you sent based on my limited understanding of GCP. Ideally, it would be good if you dont edit the pipeline code and try and provide the parameters in a `custom.config` file using the `-c` parameter. Lets see if the following works.

1. Delete your local version of the pipeline by running `rm -r ~/.nextflow/assets/nf-core/chipseq/`

2.  Create a file called `custom.config` with the following content:
```
cloud {
  driver = 'google'
  imageId = 'jkobject/global/images/dockerjava'
  instanceType = 'n1-highcpu-8'
  userName = 'jkobject'
  keyfile= '/home/jeremie/.ssh/id_rsa.pub'
}

google {
  project = 'jkobject'
  zone = 'us-east1-b'
}
```

3) Run the pipeline with the following parameters:
```
nextflow run nf-core/chipseq \\
    --input nextflow/design.csv \\
    --genome GRCh38 \\
    --single_end \\
    --seq_center DFCI \\
    --skip_diff_analysis \\
    --narrow_peak \\
    --skip_preseq \\
    --email jkobject@gmail.com \\
    --max_cpus 8 \\
    -c nextflow/nextflow.config \\
    -bucket-dir 'gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/' \\
    -resume
```

If you are using a `docker` instance on GCP you may also have to add `-profile docker` to the command. 

@evanfloden Is working on creating some documentation for using GCP with Nextflow. Any input welcome 😄

**Comment by jkobject** [comment]
Thanks so much for the help! 
Here is some progress:
```bash

[-        ] process > CheckDesign (design.csv) -
[-        ] process > MakeTSSBED               -
[-        ] process > MakeGenomeFilter         -
[-        ] process > FastQC                   -
[-        ] process > TrimGalore               -
[-        ] process > BWAMem                   -
[-        ] process > SortBAM                  -
[-        ] process > MergeBAM                 -
[-        ] process > MergeBAMFilter           -
[-        ] process > MergeBAMRemoveOrphan     -
[-        ] process > Preseq                   -
[-        ] process > CollectMultipleMetrics   -
[-        ] process > BigWig                   -
[-        ] process > PlotProfile              -
[-        ] process > PhantomPeakQualTools     -
[-        ] process > PlotFingerprint          -
[-        ] process > MACSCallPeak             -
[-        ] process > AnnotatePeaks            -
[-        ] process > PeakQC                   -
[-        ] process > ConsensusPeakSet         -
[-        ] process > ConsensusPeakSetAnnotate -
[-        ] process > ConsensusPeakSetDESeq    -
[-        ] process > IGV                      -
[-        ] process > get_software_versions    -
[-        ] process > MultiQC                  -
[-        ] process > output_documentation     -
Execution cancelled -- Finishing pending tasks before exit
WARN: Configuration setting [cloud.instanceType] is deprecated.  Please use either the process cpus/memory directives or process.machineType instead.
WARN: Invalid server response running pipeline: [actions:[[commands:[bash, -c, mkdir -p /Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4; (echo start | gsutil -q cp  -c - gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4/.command.begin || true; gsutil -m -q cp gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/stage/56/3977be46c495551541d3d4e6eb6913/design.csv /Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4/design.csv; gsutil -m -q cp gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4/.command.sh /Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4/.command.sh; gsutil -m -q cp gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4/.command.run /Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4/.command.run; mkdir -p /Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4/nextflow-bin; gsutil -m -q cp -P -r gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/tmp/2e/c6529ec3e31badcb569425bd9d1abd/* /Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4/nextflow-bin) 2>&1 > /Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4/.command.log], environment:[:], flags:[ALWAYS_RUN, IGNORE_EXIT_STATUS], imageUri:google/cloud-sdk:alpine, mounts:[[disk:nf-pipeline-work, path:/Chip_AML/nextflow/CHIPprocess_2/, readOnly:false]], name:nf-5e6a00af77e479d07691d6ce055e92e4-stage], [commands:[bash, -c, cd /Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4; bash .command.run 2>&1 | tee -a .command.log], environment:[:], flags:[IGNORE_EXIT_STATUS], imageUri:jkobject/global/images/dockerjava, mounts:[[disk:nf-pipeline-work, path:/Chip_AML/nextflow/CHIPprocess_2/, readOnly:false]], name:nf-5e6a00af77e479d07691d6ce055e92e4-main], [commands:[bash, -c, cd /Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4; [[ $GOOGLE_PIPELINE_FAILED == 1 || $NXF_DEBUG ]] && gsutil -m -q cp -R /google/ gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4 || true; gsutil -m -q cp -R design_reads.csv gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4 || true; gsutil -m -q cp -R design_controls.csv gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4 || true; [[ -f .command.trace ]] && gsutil -m -q cp -R .command.trace gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4 || true; gsutil -m -q cp -R .command.err gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4 || true; gsutil -m -q cp -R .command.out gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4 || true; gsutil -m -q cp -R .command.log gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4 || true; gsutil -m -q cp -R .exitcode gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4 || true], environment:[:], flags:[ALWAYS_RUN, IGNORE_EXIT_STATUS], imageUri:google/cloud-sdk:alpine, mounts:[[disk:nf-pipeline-work, path:/Chip_AML/nextflow/CHIPprocess_2/, readOnly:false]], name:nf-5e6a00af77e479d07691d6ce055e92e4-unstage]], resources:[projectId:jkobject, virtualMachine:[disks:[[name:nf-pipeline-work]], machineType:n1-highcpu-8, preemptible:false, serviceAccount:[scopes:[https://www.googleapis.com/auth/cloud-platform]]], zones:[us-east1-b]]]
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'CheckDesign (design.csv)'

Caused by:
  Failed to submit task with name: CheckDesign (design.csv)

Command executed:

  check_design.py design.csv design_reads.csv design_controls.csv

Command exit status:
  -

Command output:
  (empty)

Work dir:
  gs://jkobject/Chip_AML/nextflow/CHIPprocess_2/5e/6a00af77e479d07691d6ce055e92e4

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Failed to invoke `workflow.onComplete` event handler

 -- Check script '.nextflow/assets/nf-core/chipseq/main.nf' at line: 1610 or see '.nextflow.log' file for more details
````
I have entered the master node. copied my files in it and then run nextflo as explained here https://www.nextflow.io/docs/latest/google.html

However I don't know what the error means. I can have it with other tasks : 'MakeTSSBED

**Comment by drpatelh** [comment]
Hi @jkobject @evanfloden has just submitted a generic `google.config` to `nf-core/configs` which should now make it much easier to run nf-core pipelines on GCP.

Config:
https://github.com/nf-core/configs/blob/master/conf/google.config

Documentation:
https://github.com/nf-core/configs/blob/master/docs/google.md

Ill close this issue for now but please feel free to reopen if you have any issues.

**Comment by jkobject** [comment]
Hello @drpatelh,

I was able to run the pipeline very successfully locally. on many hundreds of samples.
I have not yet been able to run it on gcp clusters.

Thank you for everything! 
I will look into it.

Best,
