### ISSUE TITLE
Troubleshooting my design file 

### ISSUE THREAD

**Issue by ktrns** [nf-core/chipseq#126]
Hi there! 
Could you help me spotting the problem? The error I am getting is: 
ERROR: Please check design file: Invalid number of columns (should be 6)

Even though I specify --single-end, the output when running the pipeline says that the data type is paired-end. The design file looks like this: 
group,replicate,fastq_1,fastq_2,antibody,control
s1,1,s1.R1.fastq,,ab1,,
s2,1,s2.R1.fastq,,ab2,,
s3,1,s3.R1.fastq,,ab3,,

Is there anything wrong with it? 
Thank you very much in advance!
Katrin

**Comment by drpatelh** [comment]
Hi @ktrns Its actually `--single_end` and not `--single-end` 😄

**Comment by drpatelh** [comment]
Assuming this will solve the issue @ktrns . Feel free to reopen if it didnt :+1:

**Comment by ktrns** [comment]
Hi there! What a silly mistake of mine, sorry about that! 

The error message is still the same though. Does my toy example in the original post look ok? 

Thanks in advance! 
Katrin

**Comment by drpatelh** [comment]
Can you send me the full command you are using please? And the initial parameter output when you run the command.

**Comment by drpatelh** [comment]
Design looked ok to me on first glance but I'll run it through the same script locally when im on my laptop :+1:

**Comment by ktrns** [comment]
module load apps/nextflow/19.10.0-all
nextflow run $pathToNfcore/chipseq --single_end --input $pathToMyProject/design.csv --genome mm10 --outdir $pathToMyProject/ -with-singularity $pathToNfcore/chipseq_latest.sif -c $pathToNfcore/atacseq/conf/dcgc.config_katrin

**Comment by drpatelh** [comment]
No need 😄 . You need to remove the trailing `,` from the end of the lines. You will also need to `gzip` the `fastq` files because uncompressed input isnt a valid input for the pipeline. There dont appear to be any control samples in your design either without which the pipeline wont be able to call the peaks and so wont work either. Do you have input controls or the like you can use as a control?

Based on your example a more "correct" version would be (Ive added in a representative control sample):
```
group,replicate,fastq_1,fastq_2,antibody,control
s1,1,s1.R1.fastq.gz,,ab1,INPUT
s2,1,s2.R1.fastq.gz,,ab2,INPUT
s3,1,s3.R1.fastq.gz,,ab3,INPUT
INPUT,1,INPUT.R1.fastq.gz,,,
```

**Comment by ktrns** [comment]
I was just thinking the same: do I NEED a control? Because for the current (test) project, I don't have any. And MACS2 can call peaks without control. 

In fact, I don't have ChIP-seq data, but Cut and Run (for the first time), and I was hoping to just run the ChIP-seq pipeline as a start.

**Comment by drpatelh** [comment]
For this pipeline, currently, yes, unfortunately you do. However, you dont for the `nf-core/atacseq` pipeline. Can you send me a link to published processing methods for Cut and Run? Would be nice to add this functionality too - maybe you could create a separate issue for this?

**Comment by ktrns** [comment]
Yes, I was thinking to use the ATAC pipeline. I suppose the only difference is that for ATAC we expect big peaks, for a TF Cut and Run we expect narrow peaks. I will try to find some link. (so far I have none: I wanted to map the reads, call peaks, run HOMER - it is a test run)

**Comment by drpatelh** [comment]
```
nextflow run nf-core/atacseq \
    --input $pathToMyProject/design.csv \
    --genome mm10 \
    --single_end \
    --narrow_peak \
    --mito_name false \
    --skip_merge_replicates \
    --outdir $pathToMyProject/ \
    -with-singularity $pathToNfcore/atacseq_latest.sif \
    -c $pathToNfcore/atacseq/conf/dcgc.config_katrin
```

You can use the `--narrow_peak` parameter with the `atacseq` pipeline too. Above is a representative command.

**Comment by drpatelh** [comment]
The input design file has a different format though:
https://github.com/nf-core/atacseq/blob/master/docs/usage.md#--input

**Comment by ktrns** [comment]
Thank you, I have successfully run the atacseq pipeline.

**Comment by drpatelh** [comment]
Youre welcome :smile:
