### ISSUE TITLE
resuming to previous version

### ISSUE THREAD

**Issue by jkobject** [nf-core/chipseq#131]
Hello again, 

I ran the command with `--resume` after a memory size issue and it started back from 0 after 4 days of it running. I stopped it immediately.  I can see that the data from the first run is still there but I don't know how to tell the pipeline to resume from it. 

I tried running it with sudo and it seems that a pipeline ran with sudo, and then resumed with sudo does resume effectively. I tried to chmod the work directory but it still seems not to pick up on the cached aligned files. 

Best,

**Comment by drpatelh** [comment]
Hi @jkobject . Do you mean `-resume` because that's a Nextflow parameter and not one from the pipeline. `--resume` won't work. I'm hoping it's as simple as that...is this still on GCP?

**Comment by jkobject** [comment]
Hey, yes I used resume after but the same problem occurred.. 
I think that by running it once first with --resume, it erased some file that contained information on the state of the previous run.. and rerunning it with -resume afterward only booted it back to the previous failed attempt which had started from scratch.
 If you don't see any good alternative then I guess I have to erase all the aligned bams and rerun the pipeline..

**Comment by jkobject** [comment]
Hello, after realizing it was a nextflow issue, I went to the documentation, which solved my problem:
https://www.nextflow.io/blog/2019/demystifying-nextflow-resume.html

Thanks!
