### ISSUE TITLE
preseq lc_extrap error

### ISSUE THREAD

**Issue by drewjbeh** [nf-core/chipseq#133]
Hi there,

I am trying to run the pipeline on some Pol III ChIP-seq data from human cells and I encounter the following error from preseq: `Library expected to saturate in doubling of size, unable to extrapolate`.

According to the user manual for preseq (http://smithlabresearch.org/wp-content/uploads/manual.pdf), issue number 6 in the FAQ:

> 6. Q — When running lc extrap, I receive the error
Library expected to saturate in doubling of size, unable to extrapolate
A. — A simple two-fold extrapolation using the Good-Toulmin power series, which is within the radius of convergence and therefore rational function approximation is not needed, is performed to ensure that the sample is not overly saturated. If the Good-Toulmin formula is negative, this indicates that the library will likely completely saturate by doubling the experiment size and so extrapolation is not needed. Often this will occur if the number of reads observed twice (n2) is greater than the number of reads observed once (n1). In this case one can use simple estimators like Chao’s [1] or Zelterman’s [8] can be used to estimate the number of remaining in the library.

It seems that there is a lot of duplication in the libraries, or the libraries are close to saturation of complexity, maybe because of the low number of targets of Pol III in the genome.

There is a high rate of read alignment from bwa, and previous analysis of the data have shown high quality and good enrichment and peak numbers at Pol III sites. 
Is there anything you can suggest, or potentially a bug fix you can incorporate to work around this problem in such cases?

Thanks,
Drew

**Comment by drpatelh** [comment]
Hi @drewjbeh The easiest solution is to use the `--skip_preseq` parameter. The other QC metrics seem to be giving you a good idea as to whats going on anyway?

**Comment by drpatelh** [comment]
Closing this @drewjbeh . I think skipping this process is the only real way to solve this in order for the rest of the pipeline to complete so you can assess the results properly.

**Comment by drewjbeh** [comment]
Hi Harshil,

Sorry that I didn't reply. Skipping was the only way around this. Since we
were doing ChIP on Pol III, the low number of targets and some other issues
with library complexity were generating the errors. We have since solved
these problems. Thanks for your help.

**Comment by drpatelh** [comment]
No worries! Yep, unfortunately, its a small price to pay in order to get the rest of the results generated by the pipeline.
