### ISSUE TITLE
Create bioconda genomics packages for ngsplot DBs

### ISSUE THREAD

**Issue by apeltzer** [nf-core/chipseq#15]
See https://github.com/nf-core/chipseq/issues/2#issuecomment-393156660 for reference

According to bioconda gitter:

"Please look at the bioconductor data packages for genomes.
You can download the reference data in a post-script"

**Comment by apeltzer** [comment]
related: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bioconductor-bsgenome.hsapiens.ucsc.hg19

**Comment by apeltzer** [comment]
NGSplot is done.

**Comment by apeltzer** [comment]
+`hg19`, `hg38` and `mm10` are there. I will add these to the `environment.yml`

**Comment by ewels** [comment]
How big are these refs? Adding them to `environment.yml` means that they will be present in all containers.

I think that they're not very big though, right? So probably not a big percentage change in the container size...

**Comment by apeltzer** [comment]
~35MB (times 3) - so no, I suppose that shouldn't be an issue here!
