### ISSUE TITLE
Merge BAM fails, no error produced

### ISSUE THREAD

**Issue by lmihalj** [nf-core/chipseq#150]
Hello,

I have an issue at the Merge BAM step, but I get no errors, it just doesn't go through and it terminates the job. This is the last line from nextflow.log file: 

~> TaskHandler[id: 52; name: MergeBAM (H4K12ac_R1); status: RUNNING; exit: -; error: -; workDir: /fastscratch/myscratch/lmihalje/work/cf/1aabc8570e7f86e2382c671c7730e2]

**Comment by drpatelh** [comment]
Hi @lmihalj ! Sorry I completely missed this issue :sweat_smile: Im assuming you managed to solve the problem?

**Comment by lmihalj** [comment]
It's ok! I was using conda, so there is a glitch somewhere with picard, but then I switched to singularity and everything went smoothly!

**Comment by drpatelh** [comment]
Nice! I would have recommended for you to use Docker/Singularity anyway if possible. Glad you got it working ;)
