### ISSUE TITLE
Pipeline runs properly, but no DESeq2 output 

### ISSUE THREAD

**Issue by lmihalj** [nf-core/chipseq#151]
I have run the pipeline using singularity without any errors, but there is no deseq2 output folder in the path where it should be. MultiQC and execution reports are attached below. 
[multiqc_report.html.zip](https://github.com/nf-core/chipseq/files/4536399/multiqc_report.html.zip)
[execution_report.html.zip](https://github.com/nf-core/chipseq/files/4536410/execution_report.html.zip)

**Comment by drpatelh** [comment]
This folder will only be generated if the following conditions are met:
https://github.com/nf-core/chipseq/blob/21be3149542cdc84431e12d1e092359058aed32a/main.nf#L1309

So assuming you haven't adjusted the `--macs_gsize` and  `--skip_diff_analysis` parameters it would appear that either you don't have multiple groups/conditions or replicates to perform the differential analysis. Can you send my your input design file please?

**Comment by lmihalj** [comment]
I haven't used any of those, and yes of course, please find it attached.
[design.csv.zip](https://github.com/nf-core/chipseq/files/4536442/design.csv.zip)

**Comment by lmihalj** [comment]
Do you have any solution?

**Comment by drpatelh** [comment]
Hi @lmihalj. Sorry I completely missed the attachment you sent 😅 

The answer was actually in my previous comment - "it would appear that either you don't have multiple groups/conditions or replicates to perform the differential analysis. ". You do have replicates but you dont have multiple groups from the same antibody (e.g. `H3K14ac_WT`, `H3K14ac_KO`, etc) that can be used to perform the differential analysis. This is why that analysis isnt run and hence the folder doesnt exists.

```bash
group,replicate,fastq_1,fastq_2,antibody,control
Input,1,Input_S1_R1_001.fastq.gz,Input_S1_R2_001.fastq.gz,,
Input,2,Input_S2_R1_001.fastq.gz,Input_S2_R2_001.fastq.gz,,
Kat7,1,Kat7_S1_R1_001.fastq.gz,Kat7_S1_R2_001.fastq.gz,Kat7,Input
Kat7,2,Kat7_S2_R1_001.fastq.gz,Kat7_S2_R2_001.fastq.gz,Kat7,Input
H3K14ac,1,H3k14ac_S1_R1_001.fastq.gz,H3k14ac_S1_R2_001.fastq.gz,H3K14ac,Input
H3K14ac,2,H3k14ac_S2_R1_001.fastq.gz,H3k14ac_S2_R2_001.fastq.gz,H3K14ac,Input
H4K12ac,1,H4k12ac_S1_R1_001.fastq.gz,H4k12ac_S1_R2_001.fastq.gz,H4K12ac,Input
H4K12ac,2,H4k12ac_S2_R1_001.fastq.gz,H4k12ac_S2_R2_001.fastq.gz,H4K12ac,Input
IgG,1,IgG_S1_R1_001.fastq.gz,IgG_S1_R2_001.fastq.gz,IgG,Input
IgG,2,IgG_S2_R1_001.fastq.gz,IgG_S2_R2_001.fastq.gz,IgG,Input
```

**Comment by lmihalj** [comment]
Hi Harshil,

Thank you for your reply. I get it now, but is there any other way to check replicate correlation using this pipeline?
If the consensus peaks are called, that means they are good enough?
Thank you,
Ljubica
