### ISSUE TITLE
Images missing in Documentation

### ISSUE THREAD

**Issue by ivokwee** [nf-core/chipseq#152]
Hi. Seems images are missing in the file Documentation/results_description.html

**Comment by drpatelh** [comment]
Hi @ivokwee ! Yep, this is a bug that has been fixed on the [`dev`](https://github.com/nf-core/chipseq/blob/41b9fcce8cc9cf28ca478bec109dc324990bf4b6/main.nf#L1581) branch and will be in the next release ;) Apologies for any inconvenience. I'll close this as the issue has been fixed.
