### ISSUE TITLE
expose bwa mem -T parameter

### ISSUE THREAD

**Issue by ivokwee** [nf-core/chipseq#159]
Hi. I had a case that I needed to lower the score threshold of BWA-mem. The default is T=30 but all reads were filtered out and I had to set the T=15. Can we expose the T option in the nextflow run options?

**Comment by drpatelh** [comment]
Hi @ivokwee. Sounds like a reasonable request. Was there a reason as to why the alignments had low scores? We could either add a generic parameter e.g. `--alignment_options` or a specific one to tweak that particular option e.g. `--alignment_score`. Using the former would be much easier to integrate with Nextflow DSL 2 which is not far off now for this pipeline.

**Comment by drpatelh** [comment]
Fixed [here](https://github.com/drpatelh/chipseq/commit/15fa2feac4c46c5f59b58fe7b3f5f30897ef4071) @ivokwee. Thanks for reporting!
