### ISSUE TITLE
Error when skip_trimming

### ISSUE THREAD

**Issue by ivokwee** [nf-core/chipseq#161]
When I run the example with trimming skipped like

`nextflow run nf-core/chipseq -profile test,docker --skip_trimming
`

I get the following error (it happed also with other datasets, e.g. the Oct4/gfp dataset from https://angus.readthedocs.io/en/2019/chip-seq.html ):

```
Unknown method `ifEmpty` on ArrayList type -- Did you mean?
  isEmpty

 -- Check script '/home/kwee/.nextflow/assets/nf-core/chipseq/main.nf' at line: 1469 or see '.nextflow.log' file for more details
```

**Comment by drpatelh** [comment]
Thanks @ivokwee ! You really are putting the pipeline through its paces :slightly_frowning_face: . This has been fixed already for the next release. See [here](https://github.com/nf-core/chipseq/pull/121) Sorry, I will get around to releasing soon!
