### ISSUE TITLE
Modules required for DSL 2 implementation of pipeline

### ISSUE THREAD

**Issue by drpatelh** [nf-core/chipseq#167]
- [X] fastqc (added @drpatelh)
- [X] trimgalore (added @drpatelh)

- [X] bwa index (added @drpatelh)
- [X] bwa mem (added @drpatelh)

- [X] samtools faidx (added @drpatelh)
- [X] samtools view (added @drpatelh)
- [X] samtools sort (added @drpatelh)
- [X] samtools index (added @drpatelh)
- [X] samtools flagstat (added @drpatelh)
- [X] samtools idxstats (added @drpatelh)
- [X] samtools stats (added @drpatelh)

- [X] bedtools sort (assigned @JoseEspinosa)
- [X] bedtools complementbed (assigned @JoseEspinosa)
- [X] bedtools intersect (assigned @JoseEspinosa)
- [X] bedtools genomecov (assigned @JoseEspinosa)
- [X] bedtools merge (assigned @JoseEspinosa)

- [X] picard MergeSamFiles (added @drpatelh)
- [X] picard MarkDuplicates (added @drpatelh)
- [X] picard CollectMultipleMetrics (added @drpatelh)

- [X] deeptools computeMatrix (added @drpatelh)
- [X] deeptools plotProfile (added @drpatelh)
- [X] deeptools plotHeatmap (added @drpatelh)
- [X] deeptools plotFingerprint (added @drpatelh)

- [X] macs2 callpeak (added @drpatelh)
- [X] featureCounts (added @drpatelh)
- [X] homer annotatePeaks.pl (added @drpatelh)
- [X] bamtools filter (added @drpatelh)
- [X] bedGraphToBigWig (added @drpatelh)
- [X] preseq lc_extrap (added @drpatelh)
- [X] phantompeakqualtools (added @drpatelh)
- [X] multiqc  (added @drpatelh)

**Comment by FelixKrueger** [comment]
FastQC, Trim Galore and MultiQC should be already there, ready for plug&play.

**Comment by JoseEspinosa** [comment]
> FastQC, Trim Galore and MultiQC should be already there, ready for plug&play.

We were discussing a sort of standardization of the already implemented modules, but yes they are almost ready! 👍

**Comment by drpatelh** [comment]
I have added most of the modules now to get the chipseq pipeline running from end-to-end. Just needs some fine-tuning to resemble the parameters, inputs/outputs that we currently have for the DSL1 version `1.2.1`.
