### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by ewels** [nf-core/chipseq#18]
Currently, because we're not using Human data, the tests don't run MACS2 or the blacklisting, or several of the pipeline processes.

Replace this data with something small from Human.

**Comment by apeltzer** [comment]
HI @orzechoj  - will update the Docker/Singularity image once my conda recipe updates are built/deployed by CircleCI on bioconda - that should make continuing for you easier!

**Comment by chuan-wang** [comment]
Hi @orzechoj, with the large refactor in PR #51, now the pipeline supports MACS peak calling for all igenome references. So we can drop this task. Hopefully you haven't spent too much time on it!
