### ISSUE TITLE
Complicated design parsing

### ISSUE THREAD

**Issue by mavershang** [nf-core/chipseq#182]
Hello, I have question regarding design file for complicated experiment design as below.

In short, 3 celllines (PC9, DTP, DTP_TSA) and 2 antibodies, each condition only has one sample. Details as below. 

```
group,replicate,fastq_1,fastq_2,antibody,control
H3K9me3_PC9,1,SRR2927095_1.fastq.gz,SRR2927095_2.fastq.gz,H3K9me3_ab,PC9
H3K9me3_DTP,1,SRR2927096_1.fastq.gz,SRR2927096_2.fastq.gz,H3K9me3_ab,DTP
H3K9me3_DTP_TSA,1,SRR2927097_1.fastq.gz,SRR2927097_2.fastq.gz,H3K9me3_ab,DTP_TSA
H3K4me3_DTP,1,SRR2927098_1.fastq.gz,SRR2927098_2.fastq.gz,H3K4me3_ab,DTP
H3K4me3_DTP_TSA,1,SRR2927099_1.fastq.gz,SRR2927099_2.fastq.gz,H3K4me3_ab,DTP_TSA
PC9,1,SRR2927100_1.fastq.gz,SRR2927100_2.fastq.gz,,
DTP,1,SRR2927101_1.fastq.gz,SRR2927101_2.fastq.gz,,
DTP_TSA,1,SRR2927102_1.fastq.gz,SRR2927102_2.fastq.gz,,
```

The pipeline generated two deseq comparison for the two antibodies( H3K9me3_ab and H3K4me3_ab). But what I want to compare 
H3K9me3_PC9 vs PC9, 
H3K9me3_DTP vs DTP, 
H3K9me3_DTP_TSA vs DTP_TSA
H3K4me3_DTP vs DTP
H3K4me3_DTP_TSA vs DTP_TSA

How to solve this issue? Thanks

**Comment by drpatelh** [comment]
Hi @mavershang. Apologies for the late response, I have been on annual leave for the last week. The pipeline should only run DESeq2 if you have replicates. See `replicatesExist` variable [here](https://github.com/nf-core/chipseq/blob/0f487ed76dc947793ab48527d8d3025f5f3060a5/main.nf#L1384).

I am also a bit confused by the comparisons you listed e.g.
`H3K9me3_PC9 vs PC9` - is `H3K9me3_PC9` the IP and `PC9` is the input? If so, then the pipeline already calls the peaks in the IP relative to the input so this should be the default behaviour. Also, it seems like you have set the design file up correctly to do this already. 

If it helps please feel free to join the #chipseq channel on the [nf-core Slack workspace](https://nf-co.re/join) where we can attempt to resolve these questions/issues in real-time.
