### ISSUE TITLE
Processing single-end data caused error

### ISSUE THREAD

**Issue by mavershang** [nf-core/chipseq#185]
Hello,

I encounter an issue when dealing with single-end data. Here is the design I used:

```
group,replicate,fastq_1,fastq_2,antibody,control
DMSO,1,/hpc/grid/wip_drm_targetsciences/projects/p013_TE_Expression/GSE78206/SRR3183896.fastq.gz,,,
DMSO,2,/hpc/grid/wip_drm_targetsciences/projects/p013_TE_Expression/GSE78206/SRR3183897.fastq.gz,,,
DMSO,3,/hpc/grid/wip_drm_targetsciences/projects/p013_TE_Expression/GSE78206/SRR3183898.fastq.gz,,,
DMSO,4,/hpc/grid/wip_drm_targetsciences/projects/p013_TE_Expression/GSE78206/SRR3183899.fastq.gz,,,
DMSO,5,/hpc/grid/wip_drm_targetsciences/projects/p013_TE_Expression/GSE78206/SRR3183900.fastq.gz,,,
KDM5-C70,1,/hpc/grid/wip_drm_targetsciences/projects/p013_TE_Expression/GSE78206/SRR3183901.fastq.gz,,H3K4me3,DMSO
KDM5-C70,2,/hpc/grid/wip_drm_targetsciences/projects/p013_TE_Expression/GSE78206/SRR3183902.fastq.gz,,H3K4me3,DMSO
KDM5-C70,3,/hpc/grid/wip_drm_targetsciences/projects/p013_TE_Expression/GSE78206/SRR3183903.fastq.gz,,H3K4me3,DMSO
```
Error pop as "Argument of `file` function cannot be empty

 -- Check script '/home/shangl02/.nextflow/assets/nf-core/chipseq/main.nf' at line: 347 or see '.nextflow.log' file for more details
"
This error seems to be caused by mis-parsing of single-end/pairend data. Could any one give any suggestion?

Thanks,

**Comment by drpatelh** [comment]
Did you provide `--single_end` on the command line @mavershang ? This won't be a problem in future releases because single end will be auto-detected from the input design file.

**Comment by mavershang** [comment]
Thanks. I thought it was auto-detected. Good to learn.
