### ISSUE TITLE
bwa index error

### ISSUE THREAD

**Issue by elbakrifz** [nf-core/chipseq#186]
I was running the following command : bwa index -a bwtsw /Users/mac/Downloads/TriTrypDB-47_LmajorLV39c5_Genome.fasta, I didn't get any fichier.fasta.ann or .sa or .bwt, .amb, .pac ..
I get : [bwa_index] Pack FASTA... 0.36 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=64663060, availableWord=16549712
[BWTIncConstructFromPacked] 10 iterations done. 27298772 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 50430452 characters processed.
[bwt_gen] Finished constructing BWT in 27 iterations.
[bwa_index] 19.99 seconds elapse.
[bwa_index] Update BWT... 0.36 sec
[bwa_index] Pack forward-only FASTA... 0.22 sec
[bwa_index] Construct SA from BWT and Occ... 7.85 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index -a bwtsw /Users/mac/Downloads/TriTrypDB-47_LmajorLV39c5_Genome.fasta
[main] Real time: 31.330 sec; CPU: 28.787 sec

**Comment by drpatelh** [comment]
Hi @elbakrifz This issue doesn't seem to be related to the use of this pipeline but to building an index with BWA so will close for now! Please re-open if I misunderstood 🙂
