### ISSUE TITLE
get no such variable "design" error 

### ISSUE THREAD

**Issue by elffairy90** [nf-core/chipseq#188]
DESIGN=/mnt/projects/wlwtan/cardiac_epigenetics/foolab/jenny/scratch/chipseq/cl/ck_design_aquila.csv
CONFIG=/home/wangx/chipseq/conf/chipseq.gis.config
IGENOMES=/mnt/projects/rpd/genomes.testing/S3_igenomes/

nextflow run nf-core/chipseq -r 1.2.1 \
         --input $DESIGN --narrow_peak --igenomes_base $IGENOMES --genome GRCm38 \
         -c $CONFIG \
         -resume

this is the command I have used, I dont even have a design variable, so I dont know why I'm getting this error, please help me~

Best regards, 
Jenny

**Comment by drpatelh** [comment]
Hi @elffairy90! What are the contents of `/home/wangx/chipseq/conf/chipseq.gis.config`? This sort of error normally happens because the pipeline isn't able to find/use the software container.

**Comment by elffairy90** [comment]
Okie, I updated nextflow to 20.07.01, the old problem seems to have been solved, now I'm getting this following error:
:) please help with some suggestions again, thank you!!!


Error executing process > 'get_software_versions'

Caused by:
  Process `get_software_versions` terminated with an error exit status (127)

Command executed:

  echo 1.2.1 > v_pipeline.txt
  echo 20.07.1 > v_nextflow.txt
  fastqc --version > v_fastqc.txt
  trim_galore --version > v_trim_galore.txt
  echo $(bwa 2>&1) > v_bwa.txt
  samtools --version > v_samtools.txt
  bedtools --version > v_bedtools.txt
  echo $(bamtools --version 2>&1) > v_bamtools.txt
  echo $(plotFingerprint --version 2>&1) > v_deeptools.txt || true
  picard MarkDuplicates --version &> v_picard.txt  || true
  echo $(R --version 2>&1) > v_R.txt
  python -c "import pysam; print(pysam.__version__)" > v_pysam.txt
  echo $(macs2 --version 2>&1) > v_macs2.txt
  touch v_homer.txt
  echo $(featureCounts -v 2>&1) > v_featurecounts.txt
  preseq &> v_preseq.txt
  multiqc --version > v_multiqc.txt
  scrape_software_versions.py &> software_versions_mqc.yaml

Command exit status:
  127

Command output:
  (empty)

Command error:
  perl: symbol lookup error: /mnt/software/lib/perl5/5.10.1/auto/Cwd/Cwd.so: undefined symbol: Perl_Istack_sp_ptr

Work dir:
  /mnt/projects/wlwtan/cardiac_epigenetics/foolab/jenny/scratch/chipseq/cl/work/aa/33399aa1f83fc51fb6c3390f184ddd

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`


Best regards, 
Jenny

**Comment by drpatelh** [comment]
Hi @elffairy90 it could be a few things - my guess would be that either you aren't providing the relevant profile or config to use `docker` / `singularity` or there is a clash between the `perl` installed in the container and the one you have installed locally. I would still need to see the contents of `/home/wangx/chipseq/conf/chipseq.gis.config` to help troubleshoot because that will contain other options you have provided to be able to run the pipeline.

@jonathangoeke @cying111 @yuukiiwa are also from GIS so I am wondering whether they can help you get things running? Sorry, no idea what the compute set-up is like or whether you are actually from the same Institute. We do have a [`gis.config`](https://github.com/nf-core/configs/blob/master/conf/gis.config) on nf-core/configs but this may now be outdated so may be worth a refresh via a PR?

**Comment by jonathangoeke** [comment]
Hi @elffairy90 that very much looks like you work on our aquila cluster at GIS. We mostly run nextflow on AWS. I would recommend to run the pipeline on an environment where you have more control/administrator rights (laptop or cloud) to test that your command runs through (it might be related to the cluster set-up).

**Comment by elffairy90** [comment]
Hi @drpatelh  just to answer your question, here is the inside of the config file

/*
* -------------------------------------------------
*  Nextflow config file for GIS (Aquila)
* -------------------------------------------------
* Defines reference genomes, using iGenome paths
* Imported under the default 'standard' Nextflow
* profile in nextflow.config
*/

process {
  executor = 'sge'
  clusterOptions = { "-l mem_free=" + task.memory.toString().replaceAll(/[\sB]/,'') }
  penv = 'OpenMP'
  errorStrategy = { task.attempt < 2 ? 'retry' : 'finish' }
  // auto translate container name into conda environment name
  beforeScript = { 'source /mnt/projects/rpd/rc/init.2017-04; module load miniconda3; set +u; source activate chipseq; set -u;' }

}

params {
  saveReference = true
  // illumina iGenomes reference file paths on GIS Aquila
  igenomes_base = '/mnt/projects/aramasamy/projects/S3_igenomes/'
}

process {
  withName:TrimGalore  {
      memory = '16 GB'
      time = '72h'
  }
  withName:MergeBAM  {
      memory = '200 GB'
      time = '24h'
  }
}


Hi @jonathangoeke XD, nice to meet you here, sure, I will have a go on my own laptop. I have no idea why...


Best regards, 
Jenny

**Comment by JoseEspinosa** [comment]
I assume that this issue has been solved and will close it accordingly, if this is not the case just shout up and will happy to help 😄
