### ISSUE TITLE
Error executing process > 'BWA_MEM

### ISSUE THREAD

**Issue by ChitrArpita** [nf-core/chipseq#198]
Error executing process > 'BWA_MEM (SPT5_INPUT_R1_T1)'

Caused by:
  Process `BWA_MEM (SPT5_INPUT_R1_T1)` terminated with an error exit status (1)

Command executed:

  bwa mem \
      -t 12 \
      -M \
      -R '@RG\tID:SPT5_INPUT_R1_T1\tSM:SPT5_INPUT_R1\tPL:ILLUMINA\tLB:SPT5_INPUT_R1_T1\tPU:1' \
       \
      BWAIndex/genome.fa \
      SPT5_INPUT_R1_T1_1_val_1.fq.gz SPT5_INPUT_R1_T1_2_val_2.fq.gz \
      | samtools view -@ 12 -b -h -F 0x0100 -O BAM -o SPT5_INPUT_R1_T1.Lb.bam -

Command exit status:
  1

Command output:
  (empty)

Command error:
  [fread] Unexpected end of file
  [main_samview] fail to read the header from "-".

#### error in running with the examplefie ###

**Comment by drpatelh** [comment]
Hi @ChitrArpita ! Happy new year and sorry for the really late response 🤦🏽 Did you manage to fix this?

**Comment by e-arslan** [comment]
having the same issue!

**Comment by paolo-kunderfranco** [comment]
Dear All, I am facing the same problem, any suggestion please?
Best

**Comment by JoseEspinosa** [comment]
Hi, have you tried this? :point_down: 

> I would guess that the problem here is that the `fastq` file was not staged correctly. The solution could be to delete `work/stage` from the directory where the pipeline was run (or in the place where you `NXF_WORK` directory is set) and rerun the pipeline again. Let us know if this works, although I am afraid that we answered too late cry

**Comment by paolo-kunderfranco** [comment]
yes I tried, I removed everything, but again
  [main_samview] fail to read the header from "-".

the pipeline was working fine until 1 week ago, now it starts to give me this error.

I also repulled with nextflow pull nf-corek/sarek, nothing..
