### ISSUE TITLE
Reduce size of container

### ISSUE THREAD

**Issue by ewels** [nf-core/chipseq#20]
The container for this pipeline is kind of huge. It would be great if we could reduce the number of conda packages somehow and trim it down a bit. I'm pretty sure that there's a lot of stuff there that's not being used.

**Comment by ewels** [comment]
`mkl-2018.0.3` is by far the worst offender, coming in at `198.7 MB`

**Comment by ewels** [comment]
Yeah, top layer of docker container is `2.556GB`, not ideal..

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/chipseq/pull/77
