### ISSUE TITLE
ERROR ~ No such variable: design

### ISSUE THREAD

**Issue by amirfeizi** [nf-core/chipseq#200]
Hi there,

I am trying to run nextflow  chipseq on an inhouse linux server. The nextlofow has been installed successfully and the nextflow run hello works fine, however when I tried to run a test for chipseq pipeline I get this error, when I tried to run it with my data as input also go the same error. I appreciate your feedback.
```

 nextflow run nf-core/chipseq  -profile test
N E X T F L O W  ~  version 19.01.0
Launching `nf-core/chipseq` [crazy_brenner] - revision: 0f487ed76d [master]
WARN: Nextflow version 19.01.0 does not match workflow required version: >=19.10.0 -- Execution will continue, but things may break!
----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/chipseq v1.2.1
----------------------------------------------------

Run Name            : crazy_brenner
Data Type           : Paired-End
Design File         : https://raw.githubusercontent.com/nf-core/test-datasets/chipseq/design.csv
Genome              : Not supplied
Fasta File          : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genome.fa
GTF File            : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genes.gtf
MACS2 Genome Size   : 1.2E+7
Min Consensus Reps  : 1
MACS2 Narrow Peaks  : No
MACS2 Broad Cutoff  : 0.1
Trim R1             : 0 bp
Trim R2             : 0 bp
Trim 3' R1          : 0 bp
Trim 3' R2          : 0 bp
NextSeq Trim        : 0 bp
Fingerprint Bins    : 100
Save Genome Index   : No
Max Resources       : 6 GB memory, 2 cpus, 12h time per job
Output Dir          : ./results
Launch Dir          : /home/amir.feizi/hesam
Working Dir         : /home/amir.feizi/hesam/work
Script Dir          : /home/amir.feizi/.nextflow/assets/nf-core/chipseq
User                : amir.feizi
Config Profile      : test
Config Description  : Minimal test dataset to check pipeline function
----------------------------------------------------
ERROR ~ No such variable: design

 -- Check script 'main.nf' at line: 323 or see '.nextflow.log' file for more details

```

**Comment by drpatelh** [comment]
Hi @amirfeizi . Happy New Year!

As suggested in the error you will need to update the version of Nextflow you are using to https://github.com/nf-core/chipseq/blob/0f487ed76dc947793ab48527d8d3025f5f3060a5/nextflow.config#L171. 

Maybe it's easier to just install the latest [stable version](https://github.com/nextflow-io/nextflow/releases/tag/v20.10.0)?

If you are running on a cluster you will also need to have Singularity installed and available to the pipeline as indicated in the [Quick Start](https://github.com/nf-core/chipseq#quick-start) section of the main README.

You can then test the pipeline with:
```
nextflow run nf-core/chipseq -profile test,singularity
```

**Comment by amirfeizi** [comment]
Hi Patel,

Happy new year! and thanks for getting back to me. I have tried all and still I am getting the same error either using docker or singularity.  In the nextflow.config file line 171 the was already correct.   `nextflowVersion = '>=19.10.0'`

**Comment by drpatelh** [comment]
I believe you have it working now @amirfeizi so closing this issue :)
