### ISSUE TITLE
Without replicate how can we run the pipeline

### ISSUE THREAD

**Issue by Hemantcnaik** [nf-core/chipseq#202]
Hello, nice pipeline I have chip-seq data without replicate how can I run the pipeline and how to create the --input design file 
I have tried below command 

Error what I got 
Command output:
  ERROR: Please check design file: Replicate id not an integer!
  Line: 'EpiSC-MLL1,,~/Raw_fastq/Gene1.fastq.gz,,MLL1,EpiSC-input'

Command wrapper:
  ERROR: Please check design file: Replicate id not an integer!
  Line: 'EpiSC-MLL1,,~/Raw_fastq/Gene1.fastq.gz,,MLL1,EpiSC-input'

Work dir:
 ~/work/0b/85e81ff15ab2c88e0f3d00821a69f5

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

My chip-seq experimental data
Without treated sample
**Epics-input
EpiSC-Gene1**

With treated samples
**Epics_treated_input
EpiSC_treated_Gene1
Epics_treated_H3K4me3
Epics_treated_H3K4me1**

I don't have replicates 

how can I create design file please help me with example 

Thank you

**Comment by ryanmboileau** [comment]
Hello, 

Even if you don't have multiple replicates I think you still have to specify "1" for your replicate. You might have to also skip other steps downstream in the process but this should get you farther.

Good luck
Ryan

**Comment by JoseEspinosa** [comment]
Closed since it is answered.
