### ISSUE TITLE
Cannot read project manifest

### ISSUE THREAD

**Issue by Stakaitis** [nf-core/chipseq#212]
Hi,

I'm tryring to run `nextflow pull nf-core/chipseq -r 1.2.2` command on a server, but I'm getting and an error.

My steps:

1. `srun --pty /bin/bash` #_allocating resources_
2. `conda activate merip` #_activating my environment with nextflow and nf-core packages_
3. `nextflow pull nf-core/chipseq -r 1.2.2`

Error message:
```
Checking nf-core/chipseq ...
WARN: Cannot read project manifest -- Cause: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Cannot find `nf-core/chipseq` -- Make sure exists a GitHub repository at this address `https://github.com/nf-core/chipseq`
```
Am I doing something wrong or some kind of security certificate has to be added to the server?

Thanks,
Rytis

**Comment by Stakaitis** [comment]
This issue was fixed by the system administrator. I'm not sure what exactly he did, but now I have to include this code before starting nextflow:

`$JAVA_HOME/bin/keytool -import -alias server_name -keystore $JAVA_HOME/lib/security/cacerts -file /etc/ssl/certs/ca-bundle.crt -storepass changeit -noprompt`

However, now I'm getting a different error after `nextflow pull nf-core/chipseq -r 1.2.2`

Error:

`Checking nf-core.chipseq ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nextflow-io/nf-core.chipseq/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nextflow-io/nf-core.chipseq/contents/main.nf`

and when I run this code `nextflow run nf-core/chipseq -profile test, singularity` the pipeline starts, but crashes with the error:

`Error executing process > 'get_software_versions'

Caused by:
  Process `get_software_versions` terminated with an error exit status (127)

Command executed:

  echo 1.2.2 > v_pipeline.txt
  echo 20.10.0 > v_nextflow.txt
  fastqc --version > v_fastqc.txt
  trim_galore --version > v_trim_galore.txt
  echo $(bwa 2>&1) > v_bwa.txt
  samtools --version > v_samtools.txt
  bedtools --version > v_bedtools.txt
  echo $(bamtools --version 2>&1) > v_bamtools.txt
  echo $(plotFingerprint --version 2>&1) > v_deeptools.txt || true
  picard MarkDuplicates --version &> v_picard.txt  || true
  echo $(R --version 2>&1) > v_R.txt
  python -c "import pysam; print(pysam.__version__)" > v_pysam.txt
  echo $(macs2 --version 2>&1) > v_macs2.txt
  touch v_homer.txt
  echo $(featureCounts -v 2>&1) > v_featurecounts.txt
  preseq &> v_preseq.txt
  multiqc --version > v_multiqc.txt
  scrape_software_versions.py &> software_versions_mqc.yaml

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 4: fastqc: command not found

Work dir:
  /faststorage/project/XY-Nanopore/software/work/4f/0a71a50ec284b38696e8ee2f6859ae`

Any ideas how to fix it?

Thank You,
Rytis

**Comment by drpatelh** [comment]
Hi @Stakaitis ! You need to remove the space between `test, singularity`. With that space there Nextflow doesn't know which container engine to use and so can't find the software it needs to run the pipeline.

```console
nextflow run nf-core/chipseq -profile test,singularity
```

If you have any more problems please do come find us on [nf-core Slack](https://nf-co.re/join) in the #chipseq channel :)
