### ISSUE TITLE
Validate macsconfig inputs before starting

### ISSUE THREAD

**Issue by ewels** [nf-core/chipseq#22]
Moved from https://github.com/SciLifeLab/NGI-ChIPseq/issues/65:

Currently, we check that all FastQ input files exist (`--reads`) and that the macsconfig file exists (`--macsconfig`). However, we don't check that the sample names defined in the macsconfig file correspond to the FastQ files submitted. If wrong, this results in the pipeline running nearly to completion and then failing with a slightly obscure error message in the MACS peak calling step.

Instead, it would be good to validate that these two correspond with one another before any pipeline tasks are started, exiting with an error message immediately if something is wrong.

**Comment by chuan-wang** [comment]
Fixed in PR #51
