### ISSUE TITLE
Service: Amazon S3; Status Code: 403;

### ISSUE THREAD

**Issue by mdeloger** [nf-core/chipseq#222]
Hi all,

I just downloaded the last chipseq pipeline v1.2.2 but when I try to start it on GRCh38, here the error I have : 

Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: R2H8QVBHDTX5SE9W; S3 Extended Request ID: /YIorWddq7/a4ZSYJZeVxME+LI0KvTWMf3iXD78Zlkof+gpRoPe7q6AUrpHjcA3lswzMTW+cGwg=)

Can someone verify it can reproduce the error on his side, please ?

Thank you in davance

**Comment by JoseEspinosa** [comment]
Sorry for the late reply, this is usually related to AWS regions, if you have a ~/.aws config if you remove or rename this then stuff usually works.
