### ISSUE TITLE
deepTools - bamPEFragmentSize, plotPCA

### ISSUE THREAD

**Issue by ewels** [nf-core/chipseq#23]
Moved from https://github.com/SciLifeLab/NGI-ChIPseq/issues/54:

When running with paired-end input, it could be nice to run deepTools bamPEFragmentSize (and pick this up in the MultiQC report). See http://deeptools.readthedocs.io/en/latest/content/tools/bamPEFragmentSize.html

![dt](http://deeptools.readthedocs.io/en/latest/_images/ExampleFragmentSize.png)

Also a PCA plot using `plotPCA` - http://deeptools.readthedocs.io/en/latest/content/tools/plotPCA.html

**Needs integration into MultiQC.**

**Comment by chuan-wang** [comment]
The function `bamPEFragmentSize` was included in the pipeline (https://github.com/nf-core/chipseq/blob/master/main.nf#L594-L601). I will work on the MultiQC modules.

**Comment by chuan-wang** [comment]
Fixed in PR https://github.com/ewels/MultiQC/pull/815.
