### ISSUE TITLE
Not able to run test via docker

### ISSUE THREAD

**Issue by gregdsilva** [nf-core/chipseq#239]
HI, I am trying to run the test profile for chipseq via docker but it fails to do so and throws an error i am not able to interpret. Any ideas?

nextflow run nf-core/chipseq -profile test,docker
N E X T F L O W  ~  version 21.10.5
Launching `nf-core/chipseq` [berserk_marconi] - revision: 6924b66942 [master]
----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/chipseq v1.2.2
----------------------------------------------------

Run Name            : berserk_marconi
Data Type           : Paired-End
Design File         : https://raw.githubusercontent.com/nf-core/test-datasets/chipseq/design.csv
Genome              : Not supplied
Fasta File          : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genome.fa
GTF File            : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genes.gtf
MACS2 Genome Size   : 1.2E+7
Min Consensus Reps  : 1
MACS2 Narrow Peaks  : No
MACS2 Broad Cutoff  : 0.1
Trim R1             : 0 bp
Trim R2             : 0 bp
Trim 3' R1          : 0 bp
Trim 3' R2          : 0 bp
NextSeq Trim        : 0 bp
Fingerprint Bins    : 100
Save Genome Index   : No
Max Resources       : 6 GB memory, 2 cpus, 12h time per job
Container           : docker - nfcore/chipseq:1.2.2
Output Dir          : ./results
Launch Dir          : /home/iiser
Working Dir         : /home/iiser/work
Script Dir          : /home/iiser/.nextflow/assets/nf-core/chipseq
User                : iiser
Config Profile      : test,docker
Config Description  : Minimal test dataset to check pipeline function
----------------------------------------------------
executor >  local (6)
[e2/450af0] process > CHECK_DESIGN (design.csv)      [100%] 1 of 1, failed: 1 ✘
[83/2eb88c] process > BWA_INDEX (genome.fa)          [100%] 1 of 1, failed: 1 ✘
[05/7b2048] process > MAKE_GENE_BED (genes.gtf)      [100%] 1 of 1, failed: 1 ✘
[2e/d74c9f] process > MAKE_GENOME_FILTER (genome.fa) [100%] 1 of 1, failed: 1 ✘
[-        ] process > FASTQC                         -
[-        ] process > TRIMGALORE                     -
[-        ] process > BWA_MEM                        -
[-        ] process > SORT_BAM                       -
[-        ] process > MERGED_BAM                     -
[-        ] process > MERGED_BAM_FILTER              -
[-        ] process > MERGED_BAM_REMOVE_ORPHAN       -
[-        ] process > PRESEQ                         -
[-        ] process > PICARD_METRICS                 -
[-        ] process > BIGWIG                         -
[-        ] process > PLOTPROFILE                    -
[-        ] process > PHANTOMPEAKQUALTOOLS           -
[-        ] process > PLOTFINGERPRINT                -
[-        ] process > MACS2                          -
[-        ] process > MACS2_ANNOTATE                 -
[-        ] process > MACS2_QC                       -
[-        ] process > CONSENSUS_PEAKS                -
[-        ] process > CONSENSUS_PEAKS_ANNOTATE       -
[-        ] process > CONSENSUS_PEAKS_COUNTS         -
[-        ] process > CONSENSUS_PEAKS_DESEQ2         -
[-        ] process > IGV                            [  0%] 0 of 1
[51/586f90] process > get_software_versions          [100%] 1 of 1, failed: 1 ✘
[-        ] process > MULTIQC                        -
[5b/9969c8] process > output_documentation           [  0%] 0 of 1
Execution cancelled -- Finishing pending tasks before exit
WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
Error executing process > 'CHECK_DESIGN (design.csv)'

Caused by:
  Process `CHECK_DESIGN (design.csv)` terminated with an error exit status (126)

Command executed:

  check_design.py design.csv design_reads.csv design_controls.csv

Command exit status:
  126

Command output:
  (empty)

Command error:
  docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=nxf-vRdu9WQxYiyJ7ZFnYo4mB2jm": dial unix /var/run/docker.sock: connect: permission denied.
  See 'docker run --help'.

Work dir:
  /home/iiser/work/e2/450af0f5bf6b55991c821dba7a8837

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

java.nio.channels.ClosedByInterruptException

-[nf-core/chipseq] Pipeline completed with errors-

**Comment by JoseEspinosa** [comment]
Sorry for the late reply, in case you have not solved the issue [this](https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue) should solve the problem.

**Comment by JoseEspinosa** [comment]
I closed this issue since it has been inactive for a long time. Let us know if find any other issues.
