### ISSUE TITLE
Put phantompeaktools results in MultiQC report

### ISSUE THREAD

**Issue by ewels** [nf-core/chipseq#24]
Moved from https://github.com/SciLifeLab/NGI-ChIPseq/issues/45 (by @orzechoj):

It would be nice with a summary of fragment length etc. from phantompeaktools in multiqc too. Ideally the entire plots, but otherwise the fragment lengths and NCS and RCS numbers.

**Comment by chuan-wang** [comment]
Fixed in PR https://github.com/ewels/MultiQC/pull/814

**Comment by ewels** [comment]
I guess that there is no numeric output for the plots from this tool? It's just the PDFs? Would be great if we could plot the strand shifts in MultiQC...

**Comment by chuan-wang** [comment]
I'm testing some scripts to get the numeric output for plots. In their manual it will be .RData output. Let's see whether it will work.

**Comment by chuan-wang** [comment]
Plot function implemented in PR https://github.com/ewels/MultiQC/pull/815
