### ISSUE TITLE
Change TMPDIR variable but doesn't work

### ISSUE THREAD

**Issue by shangl02** [nf-core/chipseq#247]
Hi, the default TMPDIR point to /tmp, which does not have too much space on my workstation. Thus I changed it to 
export TMPDIR=/myNewTmpDir

But it still use /tmp as the tmp folder. is that a bug or I used the wrong variable name?

Thanks

**Comment by JoseEspinosa** [comment]
If you are using Singularity you probably need to add a custom bind path for Singularity, see this previous issue:

https://github.com/nf-core/chipseq/issues/123#issuecomment-557805550
