### ISSUE TITLE
Strand cross-correlation analysis before, or after de-duplication?

### ISSUE THREAD

**Issue by ewels** [nf-core/chipseq#25]
Moved from https://github.com/SciLifeLab/NGI-ChIPseq/issues/40 (by @sifakise):

---

According to [this publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3989762/):

> _"The evaluation of ChIP quality following duplicate removal may therefore underestimate the extent of ChIP enrichment relative to background..." ... "We recommend the assessment of RSC and NSC prior to blacklisting or duplicate removal..."_

Thus, perhaps, steps `phantompeakqualtools` and `calculateNSCRSC` could be performed on the non-deduplicated data, instead of the deduplicated?

**Comment by ewels** [comment]
Yup, that's the same publication that's linked in the original comment I think.

I'm not keen on using dedup data for some steps and not others, as originally suggested by @sifakise. But we could certainly have a `--nodedup` flag to skip the deduplication.

We're calculating NSC and RSC in the pipeline, as well as collecting % duplication stats, so then it would be up to the user to choose whether to do it or not.

Phil

**Comment by apeltzer** [comment]
Oh, sorry I didn't spot that :-( 

I'd also say keeping things consistent is better and if a user knows  whether dedup makes sense they should be able to set that with a parameter as you suggested.

**Comment by chuan-wang** [comment]
Fixed in PR #38
