### ISSUE TITLE
test run not working

### ISSUE THREAD

**Issue by stfacc** [nf-core/chipseq#273]
I tried the test run with the command:
```
nextflow run nf-core/chipseq -profile test,docker
```

It fails with the following error message:
```
No such variable: ch_design_reads_csv

 -- Check script '/home/sfacchini/.nextflow/assets/nf-core/chipseq/main.nf' at line: 346 or see '.nextflow.log' file for more details
```

Attaching the full log.
[.nextflow.log](https://github.com/nf-core/chipseq/files/8601766/default.nextflow.log)

**Comment by JoseEspinosa** [comment]
See here: https://github.com/nf-core/atacseq/issues/176#issuecomment-1111807008

**Comment by stfacc** [comment]
Confirming that the test run works with the flag `-dsl1`, thanks.

**Comment by JoseEspinosa** [comment]
Close the issue then, thanks!
