### ISSUE TITLE
Java version for Nextflow (r 1.2.1) version 20.01.0

### ISSUE THREAD

**Issue by bijuissacch224610** [nf-core/chipseq#281]
Hello Team

I am trying to replicate my old nfcore-ChipSeq run using Nextflow version 20.01.0. 
Unfortunately our server team recently updated the nextflow versions. all dependent packages including JAVA was also updated simultaneously. This has resulted in old nfcore-chipseq script not working anymore.

Can you tell me which JAVA and other packages and their version which Nextflow version 20.01.0 is using?
Any help will be appreciated.

Thanks
-Biju Issac

**Comment by JoseEspinosa** [comment]
Hi @bijuissacch224610, you can find the requirements in the documentation, see [here](https://www.nextflow.io/docs/latest/getstarted.html#requirements). 
Let us know if you have any further issues.

**Comment by JoseEspinosa** [comment]
I will close the issue now, if you have any further questions please let us know.
