### ISSUE TITLE
CHECK_DESIGN terminated with an error

### ISSUE THREAD

**Issue by CLAIRE-cuhk** [nf-core/chipseq#286]
Hello, 

I have been trying to run the nextflow/chipseq pipeline but failed due to the following error:

Error executing process > 'CHECK_DESIGN (design_combined.csv)'

Caused by:
  Process `CHECK_DESIGN (design_combined.csv)` terminated with an error exit status (1)

Command executed:

  check_design.py design_combined.csv design_reads.csv design_controls.csv

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/shared/ucl/depts/cancer/apps/nextflow_pipelines/nfcore_chipseq/chipseq-1.2.2/bin/check_design.py", line 186, in <module>
      reformat_design(DesignFile=args.DESIGN_FILE,ReadMappingFile=args.READ_MAPPING_FILE,ControlMappingFile=args.CONTROL_MAPPING_FILE)
    File "/shared/ucl/depts/cancer/apps/nextflow_pipelines/nfcore_chipseq/chipseq-1.2.2/bin/check_design.py", line 55, in reformat_design
      group,replicate,fastQFiles,antibody,control = lspl[0],lspl[1],[x for x in lspl[2:-2] if x],lspl[-2],lspl[-1]
  IndexError: list index out of range

Here is my design:
group,replicate,fastq_1,fastq_2,antibody,control
TAL1_IP,1,path toSRR443847/SRR443847.fastq.gz,,TAL1,TAL1_INPUT
TAL1_IP,2,path to SRR443848.fastq.gz,,TAL1,TAL1_INPUT
MYB_IP,1,path to SRR1603647.fastq.gz,,MYB,MYB_INPUT
MYB_IP,2,path to SRR1603653.fastq.gz,,MYB,MYB_INPUT
MYB_IP,3,path to SRR1603651.fastq.gz,,MYB,MYB_INPUT
TAL1_INPUT,1,path toSRR443856.fastq.gz,,,
TAL1_INPUT,2,path toSRR443855.fastq.gz,,,
MYB_INPUT,1,path to SRR1603649.fastq.gz,,,
MYB_INPUT,2,path to SRR1603652.fastq.gz,,,
MYB_INPUT,3,path to SRR1603648.fastq.gz,,,

It seems the pipeline couldn't recogonize design.csv although I think I followed the structure required?

Many thanks.

**Comment by JoseEspinosa** [comment]
I answered your query in slack, think that you are including an empty line at the end of the file. Let me know if this does not solve the problem.

**Comment by CLAIRE-cuhk** [comment]
Hi Jose,

Thank you! The pipeline started properly in cluster after removing the empty line at the end of design.csv.

But there is another error occured at CONSENSUS_PEAKS step. A similar issue #134 has been posted two years ago. I tried the suggested solution but still can't fix the problem. 

This is the error I receive:
[33/ab3912] process > CHECK_DESIGN (design_combin... [100%] 1 of 1, cached: 1 ✔
[fa/056c77] process > MAKE_GENOME_FILTER (genome.fa) [100%] 1 of 1, cached: 1 ✔
[23/c215e6] process > FASTQC (MYB_INPUT_R2_T1)       [100%] 10 of 10, cached:...
[ae/d850df] process > TRIMGALORE (TAL1_INPUT_R2_T1)  [100%] 10 of 10, cached:...
[8c/402e85] process > BWA_MEM (MYB_INPUT_R3_T1)      [100%] 10 of 10, cached:...
[a6/00a6fc] process > SORT_BAM (MYB_INPUT_R1_T1)     [100%] 10 of 10, cached:...
[6e/9888cb] process > MERGED_BAM (MYB_INPUT_R3)      [100%] 10 of 10, cached:...
[6b/f18bd3] process > MERGED_BAM_FILTER (MYB_INPU... [100%] 10 of 10, cached:...
[a6/e38657] process > PRESEQ (MYB_INPUT_R3)          [100%] 10 of 10, cached:...
[4e/65961c] process > PICARD_METRICS (TAL1_IP_R2)    [100%] 10 of 10, cached:...
[81/4702e2] process > BIGWIG (MYB_IP_R1)             [100%] 10 of 10, cached:...
[6a/edf300] process > PLOTPROFILE (MYB_IP_R3)        [100%] 10 of 10, cached:...
[78/dc61dc] process > PHANTOMPEAKQUALTOOLS (MYB_I... [100%] 10 of 10, cached:...
[97/87f6d2] process > PLOTFINGERPRINT (MYB_IP_R2 ... [100%] 5 of 5, cached: 4 ✔
[88/e67c93] process > MACS2 (TAL1_IP_R2 vs TAL1_I... [100%] 5 of 5, cached: 5 ✔
[2e/c28ae8] process > MACS2_ANNOTATE (MYB_IP_R3 v... [100%] 5 of 5, cached: 4 ✔
[-        ] process > MACS2_QC                       -
[90/ff2f95] process > CONSENSUS_PEAKS (MYB)          [100%] 2 of 2, failed: 1 ✘
[-        ] process > CONSENSUS_PEAKS_ANNOTATE       -
[-        ] process > CONSENSUS_PEAKS_COUNTS         -
[-        ] process > CONSENSUS_PEAKS_DESEQ2         -
[-        ] process > IGV                            -
[f1/b2b161] process > get_software_versions          [100%] 1 of 1 ✔
[-        ] process > MULTIQC                        -
[c4/765f6e] process > output_documentation           [100%] 1 of 1, cached: 1 ✔
[nf-core/chipseq] Sent summary e-mail to wly.claire2022@gmail.com (sendmail)
-[nf-core/chipseq] Pipeline completed with errors-
Waiting files transfer to complete (1 files)
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'CONSENSUS_PEAKS (TAL1)'

Caused by:
  Process `CONSENSUS_PEAKS (TAL1)` terminated with an error exit status (1)

Command executed:

  sort -T '.' -k1,1 -k2,2n TAL1_IP_R1_peaks.narrowPeak TAL1_IP_R2_peaks.narrowPeak \
      | mergeBed -c 2,3,4,5,6,7,8,9,10 -o collapse,collapse,collapse,collapse,collapse,collapse,collapse,collapse,collapse > TAL1.consensus_peaks.txt

  macs2_merged_expand.py TAL1.consensus_peaks.txt \
      TAL1_IP_R1,TAL1_IP_R2 \
      TAL1.consensus_peaks.boolean.txt \
      --min_replicates 1 \
      --is_narrow_peak

  awk -v FS='   ' -v OFS='      ' 'FNR > 1 { print $1, $2, $3, $4, "0", "+" }' TAL1.consensus_peaks.boolean.txt > TAL1.consensus_peaks.bed

  echo -e "GeneID       Chr     Start   End     Strand" > TAL1.consensus_peaks.saf
  awk -v FS='   ' -v OFS='      ' 'FNR > 1 { print $4, $1, $2, $3,  "+" }' TAL1.consensus_peaks.boolean.txt >> TAL1.consensus_peaks.saf

  plot_peak_intersect.r -i TAL1.consensus_peaks.boolean.intersect.txt -o TAL1.consensus_peaks.boolean.intersect.plot.pdf

  find * -type f -name "TAL1.consensus_peaks.bed" -exec echo -e "bwa/mergedLibrary/macs/narrowPeak/consensus/TAL1/"{}"\t0,0,0" \; > TAL1.consensus_peaks.bed.igv.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error in rowSums(Freqs[, 1:num_sets]) :
    'x' must be an array of at least two dimensions
  Calls: upset -> Counter -> [ -> [.data.frame -> rowSums
  Execution halted

Work dir:
  /lustre/scratch/scratch/ucnvlw0/TALL_Project/results_wly/CHIPSEQ_Yang/GSE29180_GSE59657_try3/work/a6/7421b82b3ad9749ba15fdd97b6c5d9

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by JoseEspinosa** [comment]
I would say that the problem might be related to #128, maybe in some files no peaks are called. You could skip this process by adding the `--skip_consensus_peaks` parameter to your command. Otherwise, you could give a try to the `dev` branch where the files without peaks are filtered (see #268). The `dev` branch should be quite stable as we are about to release.
