### ISSUE TITLE
The issue is about the install 

### ISSUE THREAD

**Issue by xiongsircool** [nf-core/chipseq#299]
-[nf-core/chipseq] Pipeline completed with errors-
i'm install this pipline in our lab server.but it have a problem. i guess that it's because the network. I don't know if there is a solution

(/media/_Extend2020/xxy/worke_chipseq) [xxy@localhost worke_chipseq]$ nextflow run nf-core/chipseq -profile test,conda
N E X T F L O W  ~  version 22.04.5
Launching `https://github.com/nf-core/chipseq` [stoic_baekeland] DSL1 - revision: 6924b66942 [master]

----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/chipseq v1.2.2
----------------------------------------------------

Run Name            : stoic_baekeland
Data Type           : Paired-End
Design File         : https://raw.githubusercontent.com/nf-core/test-datasets/chipseq/design.csv
Genome              : Not supplied
Fasta File          : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genome.fa
GTF File            : https://raw.githubusercontent.com/nf-core/test-datasets/atacseq/reference/genes.gtf
MACS2 Genome Size   : 1.2E+7
Min Consensus Reps  : 1
MACS2 Narrow Peaks  : No
MACS2 Broad Cutoff  : 0.1
Trim R1             : 0 bp
Trim R2             : 0 bp
Trim 3' R1          : 0 bp
Trim 3' R2          : 0 bp
NextSeq Trim        : 0 bp
Fingerprint Bins    : 100
Save Genome Index   : No
Max Resources       : 6 GB memory, 2 cpus, 12h time per job
Output Dir          : ./results
Launch Dir          : /media/_Extend2020/xxy/worke_chipseq
Working Dir         : /media/_Extend2020/xxy/worke_chipseq/work
Script Dir          : /home/xxy/.nextflow/assets/nf-core/chipseq
User                : xxy
Config Profile      : test,conda
Config Description  : Minimal test dataset to check pipeline function
----------------------------------------------------
[-        ] process > CHECK_DESIGN             -
[-        ] process > BWA_INDEX                -
[-        ] process > MAKE_GENE_BED            -
[-        ] process > MAKE_GENOME_FILTER       -
[-        ] process > FASTQC                   -
[-        ] process > CHECK_DESIGN             -
[-        ] process > BWA_INDEX                -
[-        ] process > MAKE_GENE_BED            -
[-        ] process > MAKE_GENOME_FILTER       -
[-        ] process > FASTQC                   -
[-        ] process > CHECK_DESIGN             -
[-        ] process > BWA_INDEX                -
[-        ] process > MAKE_GENE_BED            -
[-        ] process > MAKE_GENOME_FILTER       -
[-        ] process > FASTQC                   -
[-        ] process > CHECK_DESIGN             -
[-        ] process > BWA_INDEX                -
[-        ] process > MAKE_GENE_BED            -
[-        ] process > MAKE_GENOME_FILTER       -
[-        ] process > FASTQC                   -
[-        ] process > TRIMGALORE               -
[-        ] process > CHECK_DESIGN             -
[-        ] process > BWA_INDEX                -
[-        ] process > MAKE_GENE_BED            -
[-        ] process > MAKE_GENOME_FILTER       -
[-        ] process > FASTQC                   -
[-        ] process > TRIMGALORE               -
[-        ] process > BWA_MEM                  -
[-        ] process > SORT_BAM                 -
[-        ] process > CHECK_DESIGN             -
[-        ] process > BWA_INDEX                -
[-        ] process > MAKE_GENE_BED            -
[-        ] process > MAKE_GENOME_FILTER       -
[-        ] process > FASTQC                   -
[-        ] process > TRIMGALORE               -
[-        ] process > BWA_MEM                  -
[-        ] process > SORT_BAM                 -
[-        ] process > MERGED_BAM               -
[-        ] process > MERGED_BAM_FILTER        -
[-        ] process > MERGED_BAM_REMOVE_ORPHAN -
[-        ] process > PRESEQ                   -
[-        ] process > PICARD_METRICS           -
[-        ] process > BIGWIG                   -
[-        ] process > PLOTPROFILE              -
[-        ] process > PHANTOMPEAKQUALTOOLS     -
[-        ] process > CHECK_DESIGN             -
[-        ] process > BWA_INDEX                -
[-        ] process > MAKE_GENE_BED            -
[-        ] process > MAKE_GENOME_FILTER       -
[-        ] process > FASTQC                   -
[-        ] process > TRIMGALORE               -
[-        ] process > BWA_MEM                  -
[-        ] process > SORT_BAM                 -
[-        ] process > MERGED_BAM               -
[-        ] process > MERGED_BAM_FILTER        -
[-        ] process > MERGED_BAM_REMOVE_ORPHAN -
[-        ] process > PRESEQ                   -
[-        ] process > PICARD_METRICS           -
[-        ] process > BIGWIG                   -
[-        ] process > PLOTPROFILE              -
[-        ] process > PHANTOMPEAKQUALTOOLS     -
[-        ] process > PLOTFINGERPRINT          -
[-        ] process > MACS2                    -
[-        ] process > MACS2_ANNOTATE           -
[-        ] process > MACS2_QC                 -
[-        ] process > CONSENSUS_PEAKS          -
[-        ] process > CONSENSUS_PEAKS_ANNOTATE -
[-        ] process > CONSENSUS_PEAKS_COUNTS   -
[-        ] process > CONSENSUS_PEAKS_DESEQ2   -
[-        ] process > IGV                      -
[-        ] process > get_software_versions    -
[-        ] process > MULTIQC                  -
[-        ] process > output_documentation     -
Error executing process > 'output_documentation'

Caused by:
  Failed to create Conda environment
  command: conda env create --prefix /media/_Extend2020/xxy/worke_chipseq/work/conda/nf-core-chipseq-1.2.2-dcaaa83b75a9ed5b2ac0d32a507f2d8e --file /home/xxy/.nextflow/assets/nf-core/chipseq/environment.yml
  status : 143
  message:（Nothing）

**Comment by JoseEspinosa** [comment]
This seems to be a problem will resolving the conda environment of the pipeline which was quite huge in version 1.2.0 of the pipeline. The good news is that we just released version 2.0.0 of the pipeline yesterday so may be worth giving a try. Anyway, if possible we recommend using Docker or Singularity.
