### ISSUE TITLE
 Process `PLOTFINGERPRINT` input file name collision -- There are multiple input files for each of the following file names

### ISSUE THREAD

**Issue by ejc043** [nf-core/chipseq#301]
Hi all-- thank you for the wonder workflow! 
The pipeline was working well until the `PRESEQ` step. I tried rerunning while skipping the `PRESEQ` step but I still get the sam error with the `PLOTFINGERPRINT` step-- specifically: 

`Error executing process > 'PLOTFINGERPRINT (OA1027_Input_R1 vs OA1027_Input_R1)`

`Caused by:
  Process `PLOTFINGERPRINT` input file name collision -- There are multiple input files for each of the following file names: OA1027_Input_R1.mLb.clN.sorted.bam, OA1027_Input_R1.mLb.clN.sorted.bam.bai`

Can anyone help me sort through this issue? 
FYI-- running the test in my nf-core chipseq environment has worked fine. 

Thank you!!

**Comment by ejc043** [comment]
@adomingues Yes, it had to do with the sample files for your input. For your input files, is there anything in the "control" column? It should be empty.

**Comment by adomingues** [comment]
So simple! Thanks @ejc043, it seems to be running now 🤞🏾
