### ISSUE TITLE
Add option to use Minimap2 instead of bwa-mem

### ISSUE THREAD

**Issue by tiagochst** [nf-core/chipseq#31]
This is just a suggestion to be implemented in the future (I'm posting it here otherwise I might forget)

But Minimap2 was recently published: 
https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/bty191/4994778

And  is a much better mapper than bwa-mem. However, minimap2 is not as consistent as bwa-mem for short reads of varying quality
Soource: http://lh3.github.io/2018/04/02/minimap2-and-the-future-of-bwa

**Comment by chuan-wang** [comment]
We can put this issue on hold until there are additional studies showing the advantage of new aligners.

**Comment by drpatelh** [comment]
@tiagochst Im going to close this for now because `bwa mem` seems to be quite stable at the moment for these types of analysis. However, feel free to re-open if and when there is a future assessment that blows it out of the park :fireworks:
