### ISSUE TITLE
Metro map draft for nf-core/chipseq

### ISSUE THREAD

**Issue by G-Sarah** [nf-core/chipseq#317]
### Description of feature

Hello everyone,

Here is a metro map draft for nf-core/chipseq.

Feel free to give feedback on it and to modify it yourself if you feel like it!

I wanted to provide the svg file here but for some reason it implodes when I try to attach it so I'll make it available on the chipseq channel of the nf-core slack.

Have a nice day!

![chipseq_map_grey](https://user-images.githubusercontent.com/99276764/195793541-ecee130f-e7b9-4a4f-a42b-f3e96e96156d.png)

**Comment by JoseEspinosa** [comment]
I closed this issue since the metro map has been added in https://github.com/nf-core/chipseq/pull/327
