### ISSUE TITLE
nextflow intogen.nf error: No such variable: input 

### ISSUE THREAD

**Issue by tanayb001** [nf-core/chipseq#334]
Hi I want to use Intogen to identify the driver genes od our cohort. Below is my commands. I'm getting these errors and I'm not able to find out the reason and how to solve it.

iit@iit:~/intogen-plus$ nextflow run intogen.nf --input /home/iit/Documents/our_mutations.txt 
N E X T F L O W  ~  version 19.01.0
Launching `intogen.nf` [mighty_pauling] - revision: eb5992f5c0
WARN: Invalid config manifest attribute `doi`
WARN: There's no process matching config selector: Mutrate
ERROR ~ No such variable: input

 -- Check script 'intogen.nf' at line: 18 or see '.nextflow.log' file for more details
iit@iit:~/intogen-plus$ 

Please let me know how to solve and run it.

Thanks.

**Comment by JoseEspinosa** [comment]
I am afraid you should ask for help in the Intogen [repository](https://bitbucket.org/intogen/intogen-pipeline/src/master/) since here you can only post issues regarding the nf-core/chipseq pipeline.
