### ISSUE TITLE
MACS2 steps did not carried out

### ISSUE THREAD

**Issue by wook2014** [nf-core/chipseq#336]
### Description of the bug

I have run chipseq workflow and I can not find the MACS2 result. I have checked the log file and it seemed that the steps after deeptools did not executed.

### Command used and terminal output

```console
nextflow run ~/chipseq/nf-core-chipseq-2.0.0/workflow/ -profile singularity --input ~/chipseq/data/chipseq.csv --outdir ~/chipseq/res --fasta ~/GRCh38/GRCh38_genomic.fna --gff ~/GRCh38/GRCh38_genomic.gff --bowtie2_index ~/GRCh38/bowtie2 --gtf ~/GRCh38/GRCh38_genomic.gtf --read_length 150 --macs_gsize 2875000000 --aligner bowtie2
```

### Relevant files

[nextflow.log](https://github.com/nf-core/chipseq/files/10891931/nextflow.log)

### System information

Nextflow version ( 22.10.6 build 5843 )
Hardware ( HPC )
Executor ( pbs )
Container engine: ( Singularity )
OS ( Linux 3.10.0-862.el7.x86_64 )
Version of nf-core/chipseq ( 2.0.0)

**Comment by lesidon** [comment]
I have the same issue as the author of the reported bug. [wook2014](https://github.com/wook2014), did you find the solution?

**Comment by wook2014** [comment]
> I have the same issue as the author of the reported bug. [wook2014](https://github.com/wook2014), did you find the solution?

No, I run it in HPC and I don't have many permissions to debug it. I run it manually by different softwares myself later. but it still helps a lot, I don't need to set a lot of parameters in bwa and samtools to mapping.

**Comment by JoseEspinosa** [comment]
I will close this issue now for lack of activity, if you have any further questions please feel free to re-open it.
