### ISSUE TITLE
Problem with samplesheet

### ISSUE THREAD

**Issue by peculiar97** [nf-core/chipseq#348]
Hello,

I am trying to run the workflow using the following command:
`nextflow run nf-core/chipseq --input samplesheet_with_rep.csv --outdir nf-results-rep/ --genome mm10 --read_length 50 -profile docker`

I got this error:

> ERROR ~ Error executing process > 'NFCORE_CHIPSEQ:CHIPSEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet_with_rep.csv)'

My samplesheet:

> sample,fastq_1,fastq_2,antibody,control
STAT1_IFNg_REP1,SRR7275159_GSM3178206_WT_STAT1_90_min_IFNg_rep1_Mus_musculus_ChIP-Seq.fastq.gz,,STAT1,Input_REP1
STAT1_IFNg_REP2,SRR7275160_GSM3178207_WT_STAT1_90_min_IFNg_rep2_Mus_musculus_ChIP-Seq.fastq.gz,,STAT1,Input_REP1
STAT1_Cont_REP1,SRR7275147_GSM3178194_WT_STAT1_rep1_Mus_musculus_ChIP-Seq.fastq.gz,,STAT1,Input_REP1
STAT1_Cont_REP2,SRR7275147_GSM3178194_WT_STAT1_rep1_Mus_musculus_ChIP-Seq.fastq.gz,,STAT1,Input_REP1
Input_REP1,SRR7275146_GSM3178193_input_Mus_musculus_ChIP-Seq.fastq.gz,,,

My nextflow log file is attached below.

It seems that the pipeline is halted at samplesheet validation. Based on [this issue](https://github.com/nf-core/chipseq/issues/313#issuecomment-1523598895) I modified the samples but no luck!

Any help would be much appreciated!

[nextflow.log](https://github.com/nf-core/chipseq/files/11543526/nextflow.log)

**Comment by JoseEspinosa** [comment]
This does not seem to be problem with your sampleheet, from your log: 
```
Command executed:

  check_samplesheet.py \
      samplesheet_with_rep.csv \
      samplesheet.valid.csv
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CHIPSEQ:CHIPSEQ:INPUT_CHECK:SAMPLESHEET_CHECK":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  /bin/bash: .command.run: No such file or directory

Work dir:
  /DATA/Meta_project/chip_MQ_decker/work/c0/d6c18165870c3b11e26e7d72f13381
```

This suggest to me that It looks to me that your docker is not correctly mounting the host file system or a similar issue and thus, nextflow can not find `.command.run` the script that actually takes care of running the nextflow process.

**Comment by peculiar97** [comment]
> This does not seem to be problem with your sampleheet, from your log:
> 
> ```
> Command executed:
> 
>   check_samplesheet.py \
>       samplesheet_with_rep.csv \
>       samplesheet.valid.csv
>   
>   cat <<-END_VERSIONS > versions.yml
>   "NFCORE_CHIPSEQ:CHIPSEQ:INPUT_CHECK:SAMPLESHEET_CHECK":
>       python: $(python --version | sed 's/Python //g')
>   END_VERSIONS
> 
> Command exit status:
>   127
> 
> Command output:
>   (empty)
> 
> Command error:
>   /bin/bash: .command.run: No such file or directory
> 
> Work dir:
>   /DATA/Meta_project/chip_MQ_decker/work/c0/d6c18165870c3b11e26e7d72f13381
> ```
> 
> This suggest to me that that your docker installation is not correctly mounting the host file system or a similar issue and thus, nextflow can not find `.command.run` the script that actually takes care of running the nextflow process.

Dear Jose,
Thanks for the response!

You are right, it seems there is a problem with Docker since the pipeline works well using "singularity". I think singularity offers several advantages compared to Docker in certain use cases. For e.g. singularity enables direct interaction with the host operating system, allowing users to access hardware resources and run applications with minimal performance overhead. This feature is particularly advantageous in high-performance computing (HPC) environments where tight integration with the underlying system is crucial.

**Comment by JoseEspinosa** [comment]
Since it worked I will close the issue now. Let us know if you have any further questions.
