### ISSUE TITLE
Catch MACS error

### ISSUE THREAD

**Issue by orzechoj** [nf-core/chipseq#35]
Sometimes MACS fails because the data are so bad that it can make a model of the peaks. The error message `Too few paired peaks (0) so I can not build the model! ` is given. This causes the entire pipeline to crash, even if there is only one bad data set.

A better solution would perhaps be to report this error, but then continue?

**Comment by orzechoj** [comment]
A quick and  ugly fix is to add `errorStrategy = 'ignore'` to the `macs`job in base.config. But then we don't see which macs jobs have failed (and we ignore other errors in the macs jobs too).

**Comment by apeltzer** [comment]
Is there a special error code that MACS generates in such a case? That would be interesting to catch and issue a warning for that sample.

**Comment by ewels** [comment]
You mean an exit code? Not sure. I was saying to @orzechoj that we could implement a similar strategy to the one that we have in the rnaseq pipeline though, where we check the log files:

https://github.com/nf-core/rnaseq/blob/d64b7f536b09b400c8d46533b150c4f05843b556/main.nf#L591-L595

https://github.com/nf-core/rnaseq/blob/d64b7f536b09b400c8d46533b150c4f05843b556/main.nf#L530-L549

**Comment by apeltzer** [comment]
Yeah, exit code was in my mind actually. I thought the failing MACS process issues an exit code `!= 0`, therefore causing the pipeline to fail. If it just pushes something on `stderr`, we can implement it the way you proposed - nice :+1:

**Comment by ewels** [comment]
The problem with the exit code is that it probably doesn’t differentiate for why it fails - we only want to catch these specific failures. I could be wrong though!

**Comment by apeltzer** [comment]
I fear so, too! If I find some time I'll have a look.

**Comment by orzechoj** [comment]
The exit code is 1, which isn't so informative. But `stderr` has this error message

```
Too few paired peaks (0) so I can not build the model! Broader your MFOLD range parameter may erase this error. If it still can't build the model, we suggest to use --nomodel and --extsize 147 or other fixed number instead.
``

**Comment by drpatelh** [comment]
Closing in favour of https://github.com/nf-core/chipseq/issues/128
