### ISSUE TITLE
Process `NFCORE_CHIPSEQ:CHIPSEQ:ALIGN_BWA_MEM:BWA_MEM (EBAC_Input_REP2_T1)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by JiahuaQu** [nf-core/chipseq#355]
### Description of the bug

I submitted the job to run the nf-core chipseq in our institute's HPC, but the job always failed. 
Error executing process > 'NFCORE_CHIPSEQ:CHIPSEQ:ALIGN_BWA_MEM:BWA_MEM (EBAC_Input_REP2_T1)'

Caused by:
  Process `NFCORE_CHIPSEQ:CHIPSEQ:ALIGN_BWA_MEM:BWA_MEM (EBAC_Input_REP2_T1)` terminated with an error exit status (1)

More details in the below and attachment.
It looks like that the BWA alignment had some issues.
Hope you can help figure out my errors. Thank you.

[my_setting.config.txt](https://github.com/nf-core/chipseq/files/12018604/my_setting.config.txt)
[test.sh.txt](https://github.com/nf-core/chipseq/files/12018605/test.sh.txt)
[my.log](https://github.com/nf-core/chipseq/files/12018630/my.log)

### System information

nextflow   # version: 22.10.6
HPC
SGE
Singularity
CentOS
nf-core/chipseq v2.0.0

**Comment by JiahuaQu** [comment]
I changed from BWA to bowtie2 which didn't not produce that error. I never tried BWA any more, so I don't know whether params-file will solve this problem. Becasue bowtie will produce new error as in my follow-up question in that thread of issue in your link, perhaps I can try to change back to BWA with params-file way? Or both aligners will have the same binding issue?

**Comment by JoseEspinosa** [comment]
Fixed as mentioned [here](https://github.com/nf-core/chipseq/issues/356)
