### ISSUE TITLE
Normalisation of bigwig files

### ISSUE THREAD

**Issue by alhh507** [nf-core/chipseq#357]
### Description of feature

Hi there,

Firstly, thank you nf-core team for the development of this chip-seq pipleine. I have used it successfully multiple times, I LOVE IT.

I was just wondering about the specifics of the normalisation procedure. 

You write on the pipeline overview page  "Create normalised bigWig files scaled to 1 million mapped reads"

Does this mean that the generated bigwig files are just scaled to reads per million - or are these resulting bigwig files also normlaised to input?

If they are normalised to input are they IP-input or IP/input? Also, if they are normalised to input then is there a way to circumvent this?

Thanks and all the best,

Alex

**Comment by wanisajad** [comment]
Hi Alex,
Did you got answer for that?
Sajad

**Comment by JoseEspinosa** [comment]
Hi both,
As documented the `bigWig` files scaled to 1 million mapped reads, see [this](https://github.com/nf-core/chipseq/blob/9b4a4411053e05b4c3cfe099e23ee828bffc83f8/modules/local/bedtools_genomecov.nf#L24) line of code for reference.

**Comment by wanisajad** [comment]
@JoseEspinosa  thanks for your response.
Before plotting ChIP intensity in deepTools heatmaps, do we need to further normalize the data with the input, apart from the normalization to one million mapped reads that is already done? Would this additional step be necessary for accurate visualization of signal enrichment over background?

**Comment by JoseEspinosa** [comment]
It depends on the signal you want to identify, the current approach implemented in the pipeline is useful when comparing the overall signal intensity between different ChIP-seq experiments. By normalizing to RPM, we can ensure that variations in sequencing depth do not skew the comparison, this way we can also compare a region of interest across different samples on a similar scale. What you propose will be useful to generate fold enrichment tracks, which will indicate the relative enrichment of the ChIP sample compared to the input control in downstream analysis.

**Comment by JoseEspinosa** [comment]
I will close this issue now for lack of activity, if you have any further questions please feel free to re-open it.
