### ISSUE TITLE
All MACS jobs get the same job name

### ISSUE THREAD

**Issue by orzechoj** [nf-core/chipseq#36]
This is just a small thing, but currently all MACS jobs get the same job name. It would be good to give each job a unique name (from the macs config file).

**Comment by ewels** [comment]
This is because _all_ BAM files are linked in to every MACS process:

https://github.com/nf-core/chipseq/blob/9ecdcf4665ea3b852b9b09ec0fd7aaa0b80ecf46/main.nf#L731-L738

Simple fix is to use `chip_sample_id` for the `tag` instead. Long term we should refactor this - see #37

**Comment by chuan-wang** [comment]
Fixed in PR #38
