### ISSUE TITLE
package or namespace load failed for ‘UpSetR’ 

### ISSUE THREAD

**Issue by Nicobouch** [nf-core/chipseq#360]
### Description of the bug

I keep getting the following error using nextflow version 22.10.4 and chipseq v2.0.0
Does anyone has any idea what's going on ?
Thanks.
------------------------------------------------------
Command error:
  Error: package or namespace load failed for ‘UpSetR’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
   namespace ‘scales’ 1.1.1 is being loaded, but >= 1.2.0 is required
  Execution halted

### Command used and terminal output

```console
nextflow run nf-core/chipseq --input sample.csv --outdir test --fasta Arabidopsis_thaliana.TAIR10.dna.toplevel56.fa.gz --gff Arabidopsis_thaliana.TAIR10.56.gff.gz --macs_gsize 119667750 --read_length 150 --save_macs_pileup TRUE -profile ifb_core
```

**Comment by JoseEspinosa** [comment]
Could you provide the whole error message or the `.nextflow.log`. Also, are you using Conda to run the pipeline?

**Comment by Nicobouch** [comment]
I'm not using conda. Here is the whole error message:

________________
Error executing process > 'NFCORE_CHIPSEQ:CHIPSEQ:MACS2_CONSENSUS (H3K9)'

Caused by:
  Process `NFCORE_CHIPSEQ:CHIPSEQ:MACS2_CONSENSUS (H3K9)` terminated with an error exit status (1)

Command executed:

  sort -T '.' -k1,1 -k2,2n CONTR1_H3K9_peaks.broadPeak CONTR2_H3K9_peaks.broadPeak CONTR3_H3K9_peaks.broadPeak frim7_1_H3K9_peaks.broadPeak frim7_2_H3K9_peaks.broadPeak frim7_3_H3K9_peaks.broadPeak pom_1_H3K9_peaks.broadPeak pom_2_H3K9_peaks.broadPeak pom_3_H3K9_peaks.broadPeak \
      | mergeBed -c 2,3,4,5,6,7,8,9 -o collapse,collapse,collapse,collapse,collapse,collapse,collapse,collapse > H3K9.consensus_peaks.txt
  
  macs2_merged_expand.py \
      H3K9.consensus_peaks.txt \
      CONTR1_H3K9,CONTR2_H3K9,CONTR3_H3K9,frim7_1_H3K9,frim7_2_H3K9,frim7_3_H3K9,pom_1_H3K9,pom_2_H3K9,pom_3_H3K9 \
      H3K9.consensus_peaks.boolean.txt \
      --min_replicates 1 \
  
  
  awk -v FS='	' -v OFS='	' 'FNR > 1 { print $1, $2, $3, $4, "0", "+" }' H3K9.consensus_peaks.boolean.txt > H3K9.consensus_peaks.bed
  
  echo -e "GeneID	Chr	Start	End	Strand" > H3K9.consensus_peaks.saf
  awk -v FS='	' -v OFS='	' 'FNR > 1 { print $4, $1, $2, $3,  "+" }' H3K9.consensus_peaks.boolean.txt >> H3K9.consensus_peaks.saf
  
  plot_peak_intersect.r -i H3K9.consensus_peaks.boolean.intersect.txt -o H3K9.consensus_peaks.boolean.intersect.plot.pdf
  
  echo "H3K9.consensus_peaks.bed	H3K9/H3K9.consensus_peaks.bed" > H3K9.consensus_peaks.antibody.txt
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CHIPSEQ:CHIPSEQ:MACS2_CONSENSUS":
      python: $(python --version | sed 's/Python //g')
      r-base: $(echo $(R --version 2>&1) | sed 's/^.*R version //; s/ .*$//')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error: package or namespace load failed for ‘UpSetR’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
   namespace ‘scales’ 1.1.1 is being loaded, but >= 1.2.0 is required
  Execution halted

Work dir:
  /shared/ifbstor1/projects/project_nbouche/frim7_ChIP_CONTR/work/d0/c9bf0fd655e9a11bbae24e711026ab

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by JoseEspinosa** [comment]
I think that it could be that you have a local version of the R package installed in your environment which overwrites the one in the image (which actually meets the requirements since is 1.14). If this is the case, maybe it will be worth to remove the local version of the `UpSetR` package.

**Comment by JoseEspinosa** [comment]
I closed the issue now as it had any activity, if you need any further help feel free to reopen it.
