### ISSUE TITLE
Make subworkflows & modules available for nf-core tools

### ISSUE THREAD

**Issue by kelly-sovacool** [nf-core/chipseq#362]
### Description of the bug

I was hoping to reuse some of the local subworkflows and modules defined in this repo and install them via the nf-core tools CLI, but the `nf-core modules` and `nf-core subworkflows` commands fail because of missing information in `.nf-core.yml`.

### Command used and terminal output

```console
nf-core subworkflows --git-remote https://github.com/nf-core/chipseq.git list remote

CRITICAL 'org_path' key not present in .nf-core.yml

nf-core modules --git-remote https://github.com/nf-core/chipseq.git list remote

CRITICAL 'org_path' key not present in .nf-core.yml
```

### System information

nf-core, version 2.9

**Comment by JoseEspinosa** [comment]
Hi, sorry for the late response.
The idea of `nf-core modules` and `nf-core subworkflows` +` --git-remote` is not to install local modules or subworflows from pipelines. Instead, is for maintaining your own github repository of modules and/or subworkflows and being able to install them.
