### ISSUE TITLE
Default values for p-value and FDR

### ISSUE THREAD

**Issue by amibe1** [nf-core/chipseq#364]
### Description of feature

Hi everyone,

I am trying to find the default values for p-value and FDR when the pipeline does peak calling with MACS2. In the latest version, they are both set to "null", but I think there should be also somewhere reported default values. Anyone has any idea about this?

Thank you in advance!

**Comment by JoseEspinosa** [comment]
They don't have any default value, if either `macs_fdr` or `macs_pvalue` are not provided by the user then these arguments are not passed to the macs2 command, see [here](https://github.com/nf-core/chipseq/blob/51eba00b32885c4d0bec60db3cb0a45eb61e34c5/conf/modules.config#L530-L531).

**Comment by JoseEspinosa** [comment]
I will close this issue now for lack of activity, if you have any further questions please feel free to re-open it.
