### ISSUE TITLE
minor "samplesheet_pe.csv" format issue

### ISSUE THREAD

**Issue by hukai916** [nf-core/chipseq#369]
### Description of the bug

Very minor, I bet the last column in the following line:
https://github.com/nf-core/chipseq/blob/51eba00b32885c4d0bec60db3cb0a45eb61e34c5/assets/samplesheet_pe.csv#L2

should be:
```
WT_INPUT_REP1
```

**Comment by JoseEspinosa** [comment]
Thanks for reporting @hukai916! 
I close the issue now as this has been fixed when the new format of the `samplesheet` has been adopted in #349
