### ISSUE TITLE
Refactor MACS channel handling

### ISSUE THREAD

**Issue by ewels** [nf-core/chipseq#37]
At the moment, the `macs` process links in _all_ BAM files and then runs on just a subset:

https://github.com/nf-core/chipseq/blob/9ecdcf4665ea3b852b9b09ec0fd7aaa0b80ecf46/main.nf#L731-L738

This is not very good practice. It would be better to filter the bam channel according to the macs config and then run each MACS task with just the BAM files that will be analysed.

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/chipseq/pull/76
