### ISSUE TITLE
MACS2: Too few paired peaks (0) so I can not build the model!

### ISSUE THREAD

**Issue by dannyjwan** [nf-core/chipseq#374]
### Description of the bug

Hello, 

While running the pipeline, it is encountering issues when running MACS2. Here are the specifics:

-[nf-core/chipseq] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_CHIPSEQ:CHIPSEQ:MACS2_CALLPEAK (WT_HRCA_IP_REP1)'

Caused by:
  Process `NFCORE_CHIPSEQ:CHIPSEQ:MACS2_CALLPEAK (WT_HRCA_IP_REP1)` terminated with an error exit status (1)

Command executed:

  macs2 \
      callpeak \
      --keep-dup all --broad --broad-cutoff 0.1 \
      --gsize 1000000 \
      --format BAM \
      --name WT_HRCA_IP_REP1 \
      --treatment WT_HRCA_IP_REP1.mLb.clN.sorted.bam \
      --control WT_INPUT_REP1.mLb.clN.sorted.bam
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CHIPSEQ:CHIPSEQ:MACS2_CALLPEAK":
      macs2: $(macs2 --version | sed -e "s/macs2 //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO  @ Thu, 14 Dec 2023 23:22:41: 
  # Command line: callpeak --keep-dup all --broad --broad-cutoff 0.1 --gsize 1000000 --format BAM --name WT_HRCA_IP_REP1 --treatment WT_HRCA_IP_REP1.mLb.clN.sorted.bam --control WT_INPUT_REP1.mLb.clN.sorted.bam
  # ARGUMENTS LIST:
  # name = WT_HRCA_IP_REP1
  # format = BAM
  # ChIP-seq file = ['WT_HRCA_IP_REP1.mLb.clN.sorted.bam']
  # control file = ['WT_INPUT_REP1.mLb.clN.sorted.bam']
  # effective genome size = 1.00e+06
  # band width = 300
  # model fold = [5, 50]
  # qvalue cutoff for narrow/strong regions = 5.00e-02
  # qvalue cutoff for broad/weak regions = 1.00e-01
  # The maximum gap between significant sites is assigned as the read length/tag size.
  # The minimum length of peaks is assigned as the predicted fragment length "d".
  # Larger dataset will be scaled towards smaller dataset.
  # Range for calculating regional lambda is: 1000 bps and 10000 bps
  # Broad region calling is on
  # Paired-End mode is off
   
  INFO  @ Thu, 14 Dec 2023 23:22:41: #1 read tag files... 
  INFO  @ Thu, 14 Dec 2023 23:22:41: #1 read treatment tags... 
  INFO  @ Thu, 14 Dec 2023 23:22:43:  1000000 
  INFO  @ Thu, 14 Dec 2023 23:22:44: 1702472 reads have been read. 
  INFO  @ Thu, 14 Dec 2023 23:22:44: #1.2 read input tags... 
  INFO  @ Thu, 14 Dec 2023 23:22:45:  1000000 
  INFO  @ Thu, 14 Dec 2023 23:22:46: 1729564 reads have been read. 
  INFO  @ Thu, 14 Dec 2023 23:22:46: #1 tag size is determined as 40 bps 
  INFO  @ Thu, 14 Dec 2023 23:22:46: #1 tag size = 40.0 
  INFO  @ Thu, 14 Dec 2023 23:22:46: #1  total tags in treatment: 1702472 
  INFO  @ Thu, 14 Dec 2023 23:22:46: #1  total tags in control: 1729564 
  INFO  @ Thu, 14 Dec 2023 23:22:46: #1 finished! 
  INFO  @ Thu, 14 Dec 2023 23:22:46: #2 Build Peak Model... 
  INFO  @ Thu, 14 Dec 2023 23:22:46: #2 looking for paired plus/minus strand peaks... 
  INFO  @ Thu, 14 Dec 2023 23:22:46: #2 number of paired peaks: 0 
  WARNING @ Thu, 14 Dec 2023 23:22:46: Too few paired peaks (0) so I can not build the model! Broader your MFOLD range parameter may erase this error. If it still can't build the model, we suggest to use --nomodel and --extsize 147 or other fixed number instead. 
  WARNING @ Thu, 14 Dec 2023 23:22:46: Process for pairing-model is terminated! 

I believe this might be an issue because I am using a bacterial genome and other users on the MACS2 GitHub have reported similar problems (https://github.com/macs3-project/MACS/issues/390).

I was wondering what is the best way to resolve this issue? Thanks!

**Comment by JoseEspinosa** [comment]
I will close this issue now for lack of activity, if you have any further questions please feel free to re-open it.
