### ISSUE TITLE
Can't run if there is no control

### ISSUE THREAD

**Issue by d-jch** [nf-core/chipseq#384]
### Description of feature

I know it is recommended that every chip-seq should have an input, but there are also many experiments that choose not to sequence the input.

**Comment by JoseEspinosa** [comment]
This has been discussed several times see [this](https://nfcore.slack.com/archives/CFP55NZ5G/p1658734300720409?thread_ts=1658696265.773459&cid=CFP55NZ5G) slack thread of how to run a dataset without controls.

**Comment by JoseEspinosa** [comment]
Will close it now as it had not activity since long time.

**Comment by KunFang93** [comment]
It takes quite effort to dig out information from the link above... For people who also have same issue, the short answer might be switch to atacseq pipeline with 
```--mtio_name false --skip_merge_replicates --with_control false```

Please correct me if I have the wrong conception..
