### ISSUE TITLE
IDR analysis

### ISSUE THREAD

**Issue by ZeinBader** [nf-core/chipseq#386]
### Description of feature

Hello nf.core team.
I would like to suggest adding the IDR analysis to the pipeline to mach the ENCODE guidelines as many journals request it in the checklist these days. it will be great to add it to ChIPseq, ATACseq and all similar pipelines.

**Comment by JoseEspinosa** [comment]
Same as #87

**Comment by JoseEspinosa** [comment]
Closed in favour of #87
