### ISSUE TITLE
Can't find reference genomes for ngsplot

### ISSUE THREAD

**Issue by orzechoj** [nf-core/chipseq#43]
When I run on ngs.plot.r (using the hg19 genome), I get the following error:

```
 Error in CheckRegionAllowed(reg2plot, default.tbl) :
    Unknown region specified. Must be one of: bed
  Execution halted
```

It's the command 
```
 ngs.plot.r \
      -G hg19 \
      -R genebody \
      -C ngsplot_config \
      -O Genebody \
      -D ensembl \
      -FL 300
```

throwing the error.

Some poking around, from within the singularity container
----------------------------------------------------------

Running ngsplotdb.py shows that no genomes are installed for ngs.plot:

```
> ngsplotdb.py list
ID   Assembly Species  EnsVer   NPVer    InstalledFeatures    
>
```

But loading the nfcore-chipseq-1.0dev environment doesn't solve this, even though the hg19 genome is included the environment:

```
> source activate nfcore-chipseq-1.0dev
(nfcore-chipseq-1.0dev) > ngsplotdb.py list
ID   Assembly Species  EnsVer   NPVer    InstalledFeatures    
(nfcore-chipseq-1.0dev) > conda list
...
r-ngsplot                 2.63                          1    bioconda
r-ngsplotdb-hg19          3.00                          2    bioconda
r-ngsplotdb-hg38          3.00                          2    bioconda
r-ngsplotdb-mm10          3.00                          1    bioconda
...

```

**Comment by apeltzer** [comment]
Looks like I need to have a look at the conda package again...

**Comment by ewels** [comment]
Sounds good, thanks! 👍 

I'm slightly paranoid that this could also be affected by our conda `ENV` hack (no `source activate` so no pre/post- hook activations). But hopefully it'll be fine..

**Comment by apeltzer** [comment]
To be 100% sure, I also added the `python <3.0a0` requirement to the file. It just feels safer and better in this context. 

Yeah, I also had that feeling. Which could make things a bit more complicated in the installation unfortunately :-(

**Comment by ewels** [comment]
If anything like that does come up, then we should be able to do a workaround by mimicking those actions in the `Dockerfile` and `Singularity` file I figure.

**Comment by apeltzer** [comment]
Yup, I think that should be possible!

**Comment by apeltzer** [comment]
Hi @chuan-wang ,
I just merged in the required changes in bioconda, which should hopefully fix things without requiring that change (enforcing python2.7 to be used for the package there). 

https://github.com/bioconda/bioconda-recipes/pull/10406

**Comment by chuan-wang** [comment]
@apeltzer Good to know! Thanks for the work! XD

**Comment by apeltzer** [comment]
Still need to do some fixes with bioconda. Slighly more complex as they blacklisted all R=3.4.1 packages right now and I had to get around this first of all. 
Will keep you posted here and its high up my priority list...

**Comment by chuan-wang** [comment]
No hurry! We are still working on some bugs in the pipeline.

**Comment by chuan-wang** [comment]
@apeltzer OK! XD
