### ISSUE TITLE
Fastqc doesn't work with modules on rackham

### ISSUE THREAD

**Issue by orzechoj** [nf-core/chipseq#44]
`FastQC/0.7.2` is used in uppmax-modules.config, but this version is not installed on rackham. Change to `FastQC/0.11.2 (which is there is a module for)?

**Comment by ewels** [comment]
This is exactly the kind of reason that I would like to remove support for environment modules entirely :) As soon as the singularity image is working we can do so...

**Comment by chuan-wang** [comment]
Hi, in PR #38 I have updated all modules to the latest version in uppmax-modules.

**Comment by ewels** [comment]
As mentioned elsewhere, I think we should remove the uppmax modules profile entirely.

**Comment by chuan-wang** [comment]
This issue can be closed.
