### ISSUE TITLE
Picard doesn't work with modules on rackham

### ISSUE THREAD

**Issue by orzechoj** [nf-core/chipseq#45]
Running the picard step 

```
picard MarkDuplicates \
    INPUT=ENCFF341BPJ_chr22.sorted.bam \
    OUTPUT=ENCFF341BPJ_chr22.dedup.bam \
    ASSUME_SORTED=true \
    REMOVE_DUPLICATES=true \
    METRICS_FILE=ENCFF341BPJ_chr22.picardDupMetrics.txt \
    VALIDATION_STRINGENCY=LENIENT \
    PROGRAM_RECORD_ID='null'
```

gives `picard: command not found` error. (All modules `picard/2.10.3`, `samtools/1.5` and `BEDTools/2.26.0` seem to load ok). Changing the picard call to this command works:

```
 java -jar $PICARD_HOME/picard.jar MarkDuplicates \
    INPUT=ENCFF341BPJ_chr22.sorted.bam \
    OUTPUT=ENCFF341BPJ_chr22.dedup.bam \
    ASSUME_SORTED=true \
    REMOVE_DUPLICATES=true \
    METRICS_FILE=ENCFF341BPJ_chr22.picardDupMetrics.txt \
    VALIDATION_STRINGENCY=LENIENT \
    PROGRAM_RECORD_ID='null'
```

Not sure if we will have the same problem when running from the Docker container..

**Comment by ewels** [comment]
Probably not - this is a picard version error. Newer versions of picard use the `picard` command instead of the older style `java -jar $PICARD_HOME/picard.jar` syntax.

Version `2.10.3` of picard is pretty old (July 2017). Latest is `2.18.11`

**Comment by orzechoj** [comment]
The latest version on Uppmax is 2.10.3. So another reason not to use their modules.

**Comment by ewels** [comment]
Does the regular `uppmax` profile with singularity work ok? Any reason to use the environment modules config?

**Comment by chuan-wang** [comment]
I got the same problem with singularity on Rackham. Even when I ran under `singularity shell` I got errors can command cannot be found.

**Comment by MaxUlysse** [comment]
@chuan-wang Does your singularity image really contains picard?
I had this trouble a couple of times, but the image was corrupted, and it was empty...

**Comment by chuan-wang** [comment]
@MaxUlysse I suspect that the image was corrupted because I even cannot run fastqc or trim_galore.

**Comment by MaxUlysse** [comment]
That would make sense

**Comment by MaxUlysse** [comment]
sorry about that...

**Comment by chuan-wang** [comment]
picard worked fine by re-buiding singularity image. This issue can be closed.

**Comment by orzechoj** [comment]
Sorry if I was unclear: I got this error when running with uppmax-modules

**Comment by chuan-wang** [comment]
If you run with uppmax-modules, please pull the pipeline from my repo (https://github.com/chuan-wang/NGI-ChIPseq), and manually edit the picard command line in the file `main.nf` into `java -Xmx${avail_mem}m -jar \$PICARD_HOME/picard.jar MarkDuplicates \\`.
