### ISSUE TITLE
Time out error running BWA

### ISSUE THREAD

**Issue by orzechoj** [nf-core/chipseq#56]
I getting an error running BWA: The job seems to finish ok, with output files being written och log files indicating no error. But somehow the job is not recognized as done, so it keep on running until it's killed due to the time limit.

This was run on Uppmax/bianca, using singularity and nextflow v 0.30.1 and v0.31.0.

The last lines in `.command.log`

```
main] Version: 0.7.17-r1188
[main] CMD: bwa mem -M BWAIndex/genome.fa BEA17P061a_103_trimmed.fq.gz
[main] Real time: 219866.716 sec; CPU: 220966.991 sec
slurmstepd: error: *** JOB 7269 ON sens2017533-b107 CANCELLED AT 2018-09-30T16:10:57 DUE TO TIME LIMIT ***
```

Here's the corresponding row in the trace file:
`440	e6/1e6649	7269	bwa (BEA17P061a_103)	FAILED	-	2018-09-26 16:10:18.603	4d 15m 52s	4d 15m 47s	276.9%	6.2 GB	6.4 GB	47.4 GB	41.9 GB`

This looks very similar to this issue in the RNA-seq pipeline: https://github.com/nf-core/rnaseq/issues/81

**Comment by orzechoj** [comment]
Might be related to https://github.com/nf-core/chipseq/issues/56 and https://github.com/nf-core/rnaseq/issues/81

**Comment by orzechoj** [comment]
I found a zombie process related a bwa job

```
jacke    10397  0.0  0.0 113180   808 ?        S    Oct12   0:00      \_ /bin/bash /var/spool/slurmd/job08859/slurm_script
jacke    10400  0.0  0.0  19704  1640 ?        S    Oct12   0:00          \_ /bin/bash -c cd <proj dir>/accb27c4a175d11cdca82d54ba428a; eval export PATH="/home/jacke/bin/chipseq/bin:$PATH"; /bin/bash <proj dir>/accb27c4a175d11cdca82d54ba428a/.command.stub
jacke    10421  0.0  0.0  19912  1824 ?        S    Oct12   0:00              \_ /bin/bash <proj dir>accb27c4a175d11cdca82d54ba428a/.command.stub
jacke    10432 81.0  0.0  20008  1476 ?        R    Oct12 3140:10                  \_ /bin/bash <proj dir>accb27c4a175d11cdca82d54ba428a/.command.stub
jacke     4625  0.0  0.0      0     0 ?        Z    Oct13   0:00                      \_ [bash] <defunct>
```

I then killed the parent process, with `kill -9 10432`. But apparently nextflow didn't like that, so the bwa job was restarted:

```
Oct-15 09:19:34.325 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 8859; id: 431; name: bwa (BEA17P061a_75); status: COMPLETED; exit: 137; error: -; workDir: <proj dir>/accb27c4a175d11cdca82d54ba428a started: 1539352850686; exited: 2018-10-15T07:19:35Z; ]
Oct-15 09:19:34.614 [Task monitor] INFO  nextflow.processor.TaskProcessor - [07/accb27] NOTE: Process `bwa (BEA17P061a_75)` terminated with an error exit status (137) -- Execution is retried (1)
Oct-15 09:19:35.098 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SLURM] submitted process bwa (BEA17P061a_75) > jobId: 9313; workDir: <proj dir>/999c5ca65214f24f41b5359ba83a64
Oct-15 09:19:35.099 [Task submitter] INFO  nextflow.Session - [c9/999c5c] Re-submitted process > bwa (BEA17P061a_75)
```

**Comment by drpatelh** [comment]
@orzechoj I have updated the pipeline quite extensively now. I am using the `bwa` too but I havent seen this error yet during my multiple test runs. It could be related to the infrastructure?

Anyway, if it props up again please feel free to re-open this issue :+1:
