### ISSUE TITLE
avail_mem not used for picard

### ISSUE THREAD

**Issue by ewels** [nf-core/chipseq#57]
Since we switched to the new `picard` wrapper the `avail_mem` from nextflow is not specified in the command.

**Comment by apeltzer** [comment]
Sorry, maybe I missed the discussion: Was there an issue using the one provided by `picard` in bioconda? Or what does this refer to?

**Comment by ewels** [comment]
So basically, this code is no longer used for anything: https://github.com/nf-core/chipseq/blob/5f67d82e330c33eb2186c3210043ddbb17d8b5f2/main.nf#L479-L491

You can see that previously we ran picard with that as the memory argument (`java -Xmx${avail_mem}m`), but that was dropped when we switched to the bioconda installation: https://github.com/nf-core/chipseq/commit/4bbf815aa0806489c28a05411e0fbaa54ea26680#diff-28b7bea57b04f15beeb4c1de0ee78382L470

It's no big deal - just that we may as well delete the `avail_mem` snippet if it's not needed, or if we can specify the available memory then perhaps thats better? Not sure if it actually helps performance though. I think the bioconda script does a bunch of that anyway?

**Comment by apeltzer** [comment]
Okay, I missed that part. The bioconda recipe just adds a custom wrapper that makes it possible to run the Java Jar file with the specified amount of memory (e.g. see this script here which passes the command line parameters to the executable JAR file: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/picard/picard.sh ) 

Not sure about the performance gain here either - also I found that "limiting Java applications" in terms of CPU/Memory isn't working as expectedly all the time. Some do quite a bunch of threading that looks to some schedulers as surpassing their limits unfortunately...

**Comment by ewels** [comment]
x-ref https://github.com/nf-core/methylseq/issues/45

Required code already present [in the rnaseq pipeline](https://github.com/nf-core/rnaseq/blob/1cd5ab733a35727b01370de2ae8462d65f57fbb9/main.nf#L849-L857), so should just be a copy & paste:

```nextflow
    script:
    if( !task.memory ){
        log.info "[Picard MarkDuplicates] Available memory not known - defaulting to 3GB. Specify process memory requirements to change this."
        avail_mem = 3
    } else {
        avail_mem = task.memory.toGiga()
    }
    """
    picard -Xmx${avail_mem}g MarkDuplicates \\
```

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/chipseq/pull/61
