### ISSUE TITLE
MACS effective genome size 

### ISSUE THREAD

**Issue by tiagochst** [nf-core/chipseq#59]
For the moment, the workflow sets the `-g` from macs2 only for GRCh37 and GRCm38
https://github.com/nf-core/chipseq/blob/master/main.nf#L197-L198.

If you read macs manual (https://github.com/taoliu/MACS) this parameter has some precompiled parameters. But there are some ways to calculate this genome size as described here: https://deeptools.readthedocs.io/en/develop/content/feature/effectiveGenomeSize.html.

Since this `-g` is a number that could be either given by the user or somehow calculated, the pipeline should give more freedom so users can provide their own values, or even add more options in the workflow.

I understand that ngsplot depends on a external database (hg19, hg38 and mm10 were included in the bioconda recipe), and its use would be dependable on that. But I don't see any reason not allow users use macs2 if they give their own effective genome size.

**Comment by drpatelh** [comment]
This is in the `igenomes.config` now. 
https://github.com/nf-core/chipseq/blob/dev/conf/igenomes.config

Im not sure how they were calculated? Im assuming they are ok. Is it ok to close this now?

**Comment by ewels** [comment]
Ah nice, I think I remember talking to @chuan-wang about this now. Yes should be fine I think.
