### ISSUE TITLE
Incorrect default blacklist files

### ISSUE THREAD

**Issue by drpatelh** [nf-core/chipseq#63]
A blacklist files are provided by the ENCODE for a selection of organisms:
https://sites.google.com/site/anshulkundaje/projects/blacklists/

These rely on the fact that the assembly for the blacklist matches the one you are using with the `--genome` parameter. This is not the case for:
https://github.com/nf-core/chipseq/blob/595a689e929a08d2479fafe96a580457a16f9423/conf/igenomes.config#L37-L48

i.e. WBcel235 != ce10 and BDGP6 != dm3. 

These will either have to be removed or maybe can be used in conjuction with `liftOver` to generate the appropriate coordinates.

**Comment by chuan-wang** [comment]
Fixed in PR https://github.com/nf-core/chipseq/pull/64
