### ISSUE TITLE
plotFingerprint should only run on the bams that are used in macs process

### ISSUE THREAD

**Issue by ewels** [nf-core/chipseq#72]
Ideally, `plotFingerprint` is run on the IP and input bams that are used in the `macs` process as opposed to all of them. This will take some rejigging of the code though...
https://github.com/nf-core/chipseq/blob/b4b75ae46c2a5f814992df2dab26f0ea5245e318/main.nf#L871-L878

_Originally posted by @drpatelh in https://github.com/nf-core/chipseq/pull/71#issuecomment-472371762_

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/chipseq/pull/76
