### ISSUE TITLE
Issue with --notrim and permissions violation.

### ISSUE THREAD

**Issue by RBenRocks** [nf-core/chipseq#83]
**Error 1 - unsolved** 
When setting `--notrim`, I get the error

```
ERROR ~ No such variable: read_files_trimming

 -- Check script 'main.nf' at line: 342 or see '.nextflow.log' file for more details
```

**Error 2 - solved**
Reporting this error as it may help others when getting started with this. Not sure where to add it in the docs, so I'll leave it here. I had an error when running `nextflow run nf-core/chipseq` or `nextflow pull nfcore/chipseq` in Uppmax (`module load bioinfo-tools Nextflow`):
`nextflow pull nf-core/chipseq` throw the same error: `ERROR ~ Creating directories for /sw/apps/bioinfo/Nextflow/18.10.1/rackham/nxf_home/assets/nf-core/chipseq/.git failed`

This was solved, with help from @alneberg and @MaxUlysse by setting 
```
export NXF_LAUNCHER=$SNIC_TMP
export NXF_TEMP=$SNIC_TMP
export NXF_HOME=/my/own/path/in/rackham/ 
```

**Comment by drpatelh** [comment]
@RBenRocks I have made some major modifications to the inputs, code, docs, and functionality of the `chipseq`pipeline. I am about to merge these changes into the `master` branch so you will need to change the way that you run the pipeline i.e in terms of parameters. It should all be in the `docs` though.

This error should be taken care of after I have merged at some point today. Please do join the `chipseq` channel on our Slack workspace if you have any other issues we can help with 👍

**Comment by drpatelh** [comment]
BTW The `--notrim` parameter has been changed to `--skipTrimming`

**Comment by RBenRocks** [comment]
Thanks so much @drpatelh , really looking forward to it, it will be appreciated. I'll go ahead and close this issue, and pay attention to the new release
