### ISSUE TITLE
error when running with profile test

### ISSUE THREAD

**Issue by rrdavis77** [nf-core/chipseq#96]
I just tried running the test profile and got the following error:

`nextflow run nf-core/chipseq -profile test
`
and received this error:

```
Command executed:

  check_design.py design.csv design_reads.csv design_controls.csv

Command exit status:
  1

Command output:
  (empty)

Command error:
    File "/home/ryan/.nextflow/assets/nf-core/chipseq/bin/check_design.py", line 46
      print "{} header: {} != {}".format(ERROR_STR,','.join(header),','.join(HEADER))
                                ^
  SyntaxError: invalid syntax
```
Do I need to provide it a design file?  or does the test download one?

Thanks!

**Comment by drpatelh** [comment]
Hi @rrdavis77 . I you just use `-profile test` the pipeline will assume that you have all of the software installed locally and available on your `PATH`. Im assuming this isnt the case. Ideally, you will need to be able to use `Docker` or `Singularity` where ever you are running the pipeline. If and when you have this setup you can run the pipeline test using:
`nextflow run nf-core/chipseq -profile test,docker` or
`nextflow run nf-core/chipseq -profile test,singularity`

The error itself is coming from the fact that the `check_design.py` script has been executed with `Python 3` which Im assuming is installed locally. However, the pipeline requires `Python 2` which is the version installed in the `Docker` container.

Let me know how you get on.

**Comment by drpatelh** [comment]
You will only need to run the command above to run the tests. Providing you have an internet connection where you are running the pipeline, everything will be downloaded for you.

**Comment by rrdavis77** [comment]
Thank you @drpatelh !  I didn't think I could have two options under the flag profile.  It is running fine now!
Maybe the installation guide can elaborate and add the fact that you can add the docker or singularity option when running a test.  Thank you once again!

**Comment by drpatelh** [comment]
No probs. Yep, a quick start section like the one below will be rolled out in the next release :+1: 
https://github.com/nf-core/mnaseseq#quick-start

**Comment by drpatelh** [comment]
If you have any further issues or comments please feel free to also ping me on the `chipseq` channel on the `nf-core` workspace.
